/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ECRecoverContract } from "./ECRecover";
import { IrohaAPIContract } from "./IrohaAPI";
import { MigrationsContract } from "./Migrations";
import { StorageContract } from "./Storage";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "ECRecover"): ECRecoverContract;
      require(name: "IrohaAPI"): IrohaAPIContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "Storage"): StorageContract;
    }
  }
}

export { ECRecoverContract, ECRecoverInstance } from "./ECRecover";
export { IrohaAPIContract, IrohaAPIInstance } from "./IrohaAPI";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { StorageContract, StorageInstance } from "./Storage";
