//*
// Copyright Soramitsu Co., Ltd. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.11.2
// source: commands.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallEngine_EngineType int32

const (
	CallEngine_kSolidity CallEngine_EngineType = 0
)

// Enum value maps for CallEngine_EngineType.
var (
	CallEngine_EngineType_name = map[int32]string{
		0: "kSolidity",
	}
	CallEngine_EngineType_value = map[string]int32{
		"kSolidity": 0,
	}
)

func (x CallEngine_EngineType) Enum() *CallEngine_EngineType {
	p := new(CallEngine_EngineType)
	*p = x
	return p
}

func (x CallEngine_EngineType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallEngine_EngineType) Descriptor() protoreflect.EnumDescriptor {
	return file_commands_proto_enumTypes[0].Descriptor()
}

func (CallEngine_EngineType) Type() protoreflect.EnumType {
	return &file_commands_proto_enumTypes[0]
}

func (x CallEngine_EngineType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallEngine_EngineType.Descriptor instead.
func (CallEngine_EngineType) EnumDescriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{19, 0}
}

type AddAssetQuantity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetId string `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Amount  string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *AddAssetQuantity) Reset() {
	*x = AddAssetQuantity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commands_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddAssetQuantity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAssetQuantity) ProtoMessage() {}

func (x *AddAssetQuantity) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAssetQuantity.ProtoReflect.Descriptor instead.
func (*AddAssetQuantity) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{0}
}

func (x *AddAssetQuantity) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *AddAssetQuantity) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type AddPeer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peer *Peer `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
}

func (x *AddPeer) Reset() {
	*x = AddPeer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commands_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPeer) ProtoMessage() {}

func (x *AddPeer) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPeer.ProtoReflect.Descriptor instead.
func (*AddPeer) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{1}
}

func (x *AddPeer) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type RemovePeer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // hex string
}

func (x *RemovePeer) Reset() {
	*x = RemovePeer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commands_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemovePeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePeer) ProtoMessage() {}

func (x *RemovePeer) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePeer.ProtoReflect.Descriptor instead.
func (*RemovePeer) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{2}
}

func (x *RemovePeer) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type AddSignatory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	PublicKey string `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // hex string
}

func (x *AddSignatory) Reset() {
	*x = AddSignatory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commands_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSignatory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSignatory) ProtoMessage() {}

func (x *AddSignatory) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSignatory.ProtoReflect.Descriptor instead.
func (*AddSignatory) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{3}
}

func (x *AddSignatory) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AddSignatory) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type CreateAsset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetName string `protobuf:"bytes,1,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`
	DomainId  string `protobuf:"bytes,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	Precision uint32 `protobuf:"varint,3,opt,name=precision,proto3" json:"precision,omitempty"`
}

func (x *CreateAsset) Reset() {
	*x = CreateAsset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commands_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAsset) ProtoMessage() {}

func (x *CreateAsset) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAsset.ProtoReflect.Descriptor instead.
func (*CreateAsset) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAsset) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *CreateAsset) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

func (x *CreateAsset) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

type CreateAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountName string `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	DomainId    string `protobuf:"bytes,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	PublicKey   string `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // hex string
}

func (x *CreateAccount) Reset() {
	*x = CreateAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commands_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccount) ProtoMessage() {}

func (x *CreateAccount) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccount.ProtoReflect.Descriptor instead.
func (*CreateAccount) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAccount) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *CreateAccount) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

func (x *CreateAccount) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type SetAccountDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Key       string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value     string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SetAccountDetail) Reset() {
	*x = SetAccountDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commands_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAccountDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAccountDetail) ProtoMessage() {}

func (x *SetAccountDetail) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAccountDetail.ProtoReflect.Descriptor instead.
func (*SetAccountDetail) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{6}
}

func (x *SetAccountDetail) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SetAccountDetail) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetAccountDetail) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CreateDomain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DomainId    string `protobuf:"bytes,1,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	DefaultRole string `protobuf:"bytes,2,opt,name=default_role,json=defaultRole,proto3" json:"default_role,omitempty"`
}

func (x *CreateDomain) Reset() {
	*x = CreateDomain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commands_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDomain) ProtoMessage() {}

func (x *CreateDomain) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDomain.ProtoReflect.Descriptor instead.
func (*CreateDomain) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{7}
}

func (x *CreateDomain) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

func (x *CreateDomain) GetDefaultRole() string {
	if x != nil {
		return x.DefaultRole
	}
	return ""
}

type RemoveSignatory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	PublicKey string `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // hex string
}

func (x *RemoveSignatory) Reset() {
	*x = RemoveSignatory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commands_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveSignatory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSignatory) ProtoMessage() {}

func (x *RemoveSignatory) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSignatory.ProtoReflect.Descriptor instead.
func (*RemoveSignatory) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveSignatory) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RemoveSignatory) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type SetAccountQuorum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Quorum    uint32 `protobuf:"varint,2,opt,name=quorum,proto3" json:"quorum,omitempty"`
}

func (x *SetAccountQuorum) Reset() {
	*x = SetAccountQuorum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commands_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAccountQuorum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAccountQuorum) ProtoMessage() {}

func (x *SetAccountQuorum) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAccountQuorum.ProtoReflect.Descriptor instead.
func (*SetAccountQuorum) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{9}
}

func (x *SetAccountQuorum) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SetAccountQuorum) GetQuorum() uint32 {
	if x != nil {
		return x.Quorum
	}
	return 0
}

type TransferAsset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcAccountId  string `protobuf:"bytes,1,opt,name=src_account_id,json=srcAccountId,proto3" json:"src_account_id,omitempty"`
	DestAccountId string `protobuf:"bytes,2,opt,name=dest_account_id,json=destAccountId,proto3" json:"dest_account_id,omitempty"`
	AssetId       string `protobuf:"bytes,3,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Description   string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Amount        string `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *TransferAsset) Reset() {
	*x = TransferAsset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commands_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferAsset) ProtoMessage() {}

func (x *TransferAsset) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferAsset.ProtoReflect.Descriptor instead.
func (*TransferAsset) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{10}
}

func (x *TransferAsset) GetSrcAccountId() string {
	if x != nil {
		return x.SrcAccountId
	}
	return ""
}

func (x *TransferAsset) GetDestAccountId() string {
	if x != nil {
		return x.DestAccountId
	}
	return ""
}

func (x *TransferAsset) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *TransferAsset) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TransferAsset) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type AppendRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	RoleName  string `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
}

func (x *AppendRole) Reset() {
	*x = AppendRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commands_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppendRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRole) ProtoMessage() {}

func (x *AppendRole) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRole.ProtoReflect.Descriptor instead.
func (*AppendRole) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{11}
}

func (x *AppendRole) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AppendRole) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type DetachRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	RoleName  string `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
}

func (x *DetachRole) Reset() {
	*x = DetachRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commands_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetachRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachRole) ProtoMessage() {}

func (x *DetachRole) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachRole.ProtoReflect.Descriptor instead.
func (*DetachRole) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{12}
}

func (x *DetachRole) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DetachRole) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type CreateRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleName    string           `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Permissions []RolePermission `protobuf:"varint,2,rep,packed,name=permissions,proto3,enum=iroha.protocol.RolePermission" json:"permissions,omitempty"`
}

func (x *CreateRole) Reset() {
	*x = CreateRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commands_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRole) ProtoMessage() {}

func (x *CreateRole) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRole.ProtoReflect.Descriptor instead.
func (*CreateRole) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{13}
}

func (x *CreateRole) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *CreateRole) GetPermissions() []RolePermission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type GrantPermission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId  string              `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Permission GrantablePermission `protobuf:"varint,2,opt,name=permission,proto3,enum=iroha.protocol.GrantablePermission" json:"permission,omitempty"`
}

func (x *GrantPermission) Reset() {
	*x = GrantPermission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commands_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrantPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantPermission) ProtoMessage() {}

func (x *GrantPermission) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantPermission.ProtoReflect.Descriptor instead.
func (*GrantPermission) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{14}
}

func (x *GrantPermission) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GrantPermission) GetPermission() GrantablePermission {
	if x != nil {
		return x.Permission
	}
	return GrantablePermission_can_add_my_signatory
}

type RevokePermission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId  string              `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Permission GrantablePermission `protobuf:"varint,2,opt,name=permission,proto3,enum=iroha.protocol.GrantablePermission" json:"permission,omitempty"`
}

func (x *RevokePermission) Reset() {
	*x = RevokePermission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commands_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokePermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokePermission) ProtoMessage() {}

func (x *RevokePermission) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokePermission.ProtoReflect.Descriptor instead.
func (*RevokePermission) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{15}
}

func (x *RevokePermission) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RevokePermission) GetPermission() GrantablePermission {
	if x != nil {
		return x.Permission
	}
	return GrantablePermission_can_add_my_signatory
}

type SubtractAssetQuantity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetId string `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Amount  string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *SubtractAssetQuantity) Reset() {
	*x = SubtractAssetQuantity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commands_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubtractAssetQuantity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtractAssetQuantity) ProtoMessage() {}

func (x *SubtractAssetQuantity) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtractAssetQuantity.ProtoReflect.Descriptor instead.
func (*SubtractAssetQuantity) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{16}
}

func (x *SubtractAssetQuantity) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *SubtractAssetQuantity) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type CompareAndSetAccountDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Key       string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value     string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Types that are assignable to OptOldValue:
	//	*CompareAndSetAccountDetail_OldValue
	OptOldValue isCompareAndSetAccountDetail_OptOldValue `protobuf_oneof:"opt_old_value"`
	CheckEmpty  bool                                     `protobuf:"varint,5,opt,name=check_empty,json=checkEmpty,proto3" json:"check_empty,omitempty"`
}

func (x *CompareAndSetAccountDetail) Reset() {
	*x = CompareAndSetAccountDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commands_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompareAndSetAccountDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompareAndSetAccountDetail) ProtoMessage() {}

func (x *CompareAndSetAccountDetail) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompareAndSetAccountDetail.ProtoReflect.Descriptor instead.
func (*CompareAndSetAccountDetail) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{17}
}

func (x *CompareAndSetAccountDetail) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CompareAndSetAccountDetail) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CompareAndSetAccountDetail) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (m *CompareAndSetAccountDetail) GetOptOldValue() isCompareAndSetAccountDetail_OptOldValue {
	if m != nil {
		return m.OptOldValue
	}
	return nil
}

func (x *CompareAndSetAccountDetail) GetOldValue() string {
	if x, ok := x.GetOptOldValue().(*CompareAndSetAccountDetail_OldValue); ok {
		return x.OldValue
	}
	return ""
}

func (x *CompareAndSetAccountDetail) GetCheckEmpty() bool {
	if x != nil {
		return x.CheckEmpty
	}
	return false
}

type isCompareAndSetAccountDetail_OptOldValue interface {
	isCompareAndSetAccountDetail_OptOldValue()
}

type CompareAndSetAccountDetail_OldValue struct {
	OldValue string `protobuf:"bytes,4,opt,name=old_value,json=oldValue,proto3,oneof"`
}

func (*CompareAndSetAccountDetail_OldValue) isCompareAndSetAccountDetail_OptOldValue() {}

type SetSettingValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SetSettingValue) Reset() {
	*x = SetSettingValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commands_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSettingValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSettingValue) ProtoMessage() {}

func (x *SetSettingValue) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSettingValue.ProtoReflect.Descriptor instead.
func (*SetSettingValue) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{18}
}

func (x *SetSettingValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetSettingValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CallEngine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   CallEngine_EngineType `protobuf:"varint,1,opt,name=type,proto3,enum=iroha.protocol.CallEngine_EngineType" json:"type,omitempty"`
	Caller string                `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`
	//    oneof opt_callee {
	//      string callee = 3;  // hex string
	//    }
	Callee string `protobuf:"bytes,3,opt,name=callee,proto3" json:"callee,omitempty"` // hex string
	Input  string `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`   // hex string
}

func (x *CallEngine) Reset() {
	*x = CallEngine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commands_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallEngine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallEngine) ProtoMessage() {}

func (x *CallEngine) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallEngine.ProtoReflect.Descriptor instead.
func (*CallEngine) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{19}
}

func (x *CallEngine) GetType() CallEngine_EngineType {
	if x != nil {
		return x.Type
	}
	return CallEngine_kSolidity
}

func (x *CallEngine) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *CallEngine) GetCallee() string {
	if x != nil {
		return x.Callee
	}
	return ""
}

func (x *CallEngine) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Command:
	//	*Command_AddAssetQuantity
	//	*Command_AddPeer
	//	*Command_AddSignatory
	//	*Command_AppendRole
	//	*Command_CreateAccount
	//	*Command_CreateAsset
	//	*Command_CreateDomain
	//	*Command_CreateRole
	//	*Command_DetachRole
	//	*Command_GrantPermission
	//	*Command_RemoveSignatory
	//	*Command_RevokePermission
	//	*Command_SetAccountDetail
	//	*Command_SetAccountQuorum
	//	*Command_SubtractAssetQuantity
	//	*Command_TransferAsset
	//	*Command_RemovePeer
	//	*Command_CompareAndSetAccountDetail
	//	*Command_SetSettingValue
	//	*Command_CallEngine
	Command isCommand_Command `protobuf_oneof:"command"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commands_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_commands_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_commands_proto_rawDescGZIP(), []int{20}
}

func (m *Command) GetCommand() isCommand_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (x *Command) GetAddAssetQuantity() *AddAssetQuantity {
	if x, ok := x.GetCommand().(*Command_AddAssetQuantity); ok {
		return x.AddAssetQuantity
	}
	return nil
}

func (x *Command) GetAddPeer() *AddPeer {
	if x, ok := x.GetCommand().(*Command_AddPeer); ok {
		return x.AddPeer
	}
	return nil
}

func (x *Command) GetAddSignatory() *AddSignatory {
	if x, ok := x.GetCommand().(*Command_AddSignatory); ok {
		return x.AddSignatory
	}
	return nil
}

func (x *Command) GetAppendRole() *AppendRole {
	if x, ok := x.GetCommand().(*Command_AppendRole); ok {
		return x.AppendRole
	}
	return nil
}

func (x *Command) GetCreateAccount() *CreateAccount {
	if x, ok := x.GetCommand().(*Command_CreateAccount); ok {
		return x.CreateAccount
	}
	return nil
}

func (x *Command) GetCreateAsset() *CreateAsset {
	if x, ok := x.GetCommand().(*Command_CreateAsset); ok {
		return x.CreateAsset
	}
	return nil
}

func (x *Command) GetCreateDomain() *CreateDomain {
	if x, ok := x.GetCommand().(*Command_CreateDomain); ok {
		return x.CreateDomain
	}
	return nil
}

func (x *Command) GetCreateRole() *CreateRole {
	if x, ok := x.GetCommand().(*Command_CreateRole); ok {
		return x.CreateRole
	}
	return nil
}

func (x *Command) GetDetachRole() *DetachRole {
	if x, ok := x.GetCommand().(*Command_DetachRole); ok {
		return x.DetachRole
	}
	return nil
}

func (x *Command) GetGrantPermission() *GrantPermission {
	if x, ok := x.GetCommand().(*Command_GrantPermission); ok {
		return x.GrantPermission
	}
	return nil
}

func (x *Command) GetRemoveSignatory() *RemoveSignatory {
	if x, ok := x.GetCommand().(*Command_RemoveSignatory); ok {
		return x.RemoveSignatory
	}
	return nil
}

func (x *Command) GetRevokePermission() *RevokePermission {
	if x, ok := x.GetCommand().(*Command_RevokePermission); ok {
		return x.RevokePermission
	}
	return nil
}

func (x *Command) GetSetAccountDetail() *SetAccountDetail {
	if x, ok := x.GetCommand().(*Command_SetAccountDetail); ok {
		return x.SetAccountDetail
	}
	return nil
}

func (x *Command) GetSetAccountQuorum() *SetAccountQuorum {
	if x, ok := x.GetCommand().(*Command_SetAccountQuorum); ok {
		return x.SetAccountQuorum
	}
	return nil
}

func (x *Command) GetSubtractAssetQuantity() *SubtractAssetQuantity {
	if x, ok := x.GetCommand().(*Command_SubtractAssetQuantity); ok {
		return x.SubtractAssetQuantity
	}
	return nil
}

func (x *Command) GetTransferAsset() *TransferAsset {
	if x, ok := x.GetCommand().(*Command_TransferAsset); ok {
		return x.TransferAsset
	}
	return nil
}

func (x *Command) GetRemovePeer() *RemovePeer {
	if x, ok := x.GetCommand().(*Command_RemovePeer); ok {
		return x.RemovePeer
	}
	return nil
}

func (x *Command) GetCompareAndSetAccountDetail() *CompareAndSetAccountDetail {
	if x, ok := x.GetCommand().(*Command_CompareAndSetAccountDetail); ok {
		return x.CompareAndSetAccountDetail
	}
	return nil
}

func (x *Command) GetSetSettingValue() *SetSettingValue {
	if x, ok := x.GetCommand().(*Command_SetSettingValue); ok {
		return x.SetSettingValue
	}
	return nil
}

func (x *Command) GetCallEngine() *CallEngine {
	if x, ok := x.GetCommand().(*Command_CallEngine); ok {
		return x.CallEngine
	}
	return nil
}

type isCommand_Command interface {
	isCommand_Command()
}

type Command_AddAssetQuantity struct {
	AddAssetQuantity *AddAssetQuantity `protobuf:"bytes,1,opt,name=add_asset_quantity,json=addAssetQuantity,proto3,oneof"`
}

type Command_AddPeer struct {
	AddPeer *AddPeer `protobuf:"bytes,2,opt,name=add_peer,json=addPeer,proto3,oneof"`
}

type Command_AddSignatory struct {
	AddSignatory *AddSignatory `protobuf:"bytes,3,opt,name=add_signatory,json=addSignatory,proto3,oneof"`
}

type Command_AppendRole struct {
	AppendRole *AppendRole `protobuf:"bytes,4,opt,name=append_role,json=appendRole,proto3,oneof"`
}

type Command_CreateAccount struct {
	CreateAccount *CreateAccount `protobuf:"bytes,5,opt,name=create_account,json=createAccount,proto3,oneof"`
}

type Command_CreateAsset struct {
	CreateAsset *CreateAsset `protobuf:"bytes,6,opt,name=create_asset,json=createAsset,proto3,oneof"`
}

type Command_CreateDomain struct {
	CreateDomain *CreateDomain `protobuf:"bytes,7,opt,name=create_domain,json=createDomain,proto3,oneof"`
}

type Command_CreateRole struct {
	CreateRole *CreateRole `protobuf:"bytes,8,opt,name=create_role,json=createRole,proto3,oneof"`
}

type Command_DetachRole struct {
	DetachRole *DetachRole `protobuf:"bytes,9,opt,name=detach_role,json=detachRole,proto3,oneof"`
}

type Command_GrantPermission struct {
	GrantPermission *GrantPermission `protobuf:"bytes,10,opt,name=grant_permission,json=grantPermission,proto3,oneof"`
}

type Command_RemoveSignatory struct {
	RemoveSignatory *RemoveSignatory `protobuf:"bytes,11,opt,name=remove_signatory,json=removeSignatory,proto3,oneof"`
}

type Command_RevokePermission struct {
	RevokePermission *RevokePermission `protobuf:"bytes,12,opt,name=revoke_permission,json=revokePermission,proto3,oneof"`
}

type Command_SetAccountDetail struct {
	SetAccountDetail *SetAccountDetail `protobuf:"bytes,13,opt,name=set_account_detail,json=setAccountDetail,proto3,oneof"`
}

type Command_SetAccountQuorum struct {
	SetAccountQuorum *SetAccountQuorum `protobuf:"bytes,14,opt,name=set_account_quorum,json=setAccountQuorum,proto3,oneof"`
}

type Command_SubtractAssetQuantity struct {
	SubtractAssetQuantity *SubtractAssetQuantity `protobuf:"bytes,15,opt,name=subtract_asset_quantity,json=subtractAssetQuantity,proto3,oneof"`
}

type Command_TransferAsset struct {
	TransferAsset *TransferAsset `protobuf:"bytes,16,opt,name=transfer_asset,json=transferAsset,proto3,oneof"`
}

type Command_RemovePeer struct {
	RemovePeer *RemovePeer `protobuf:"bytes,17,opt,name=remove_peer,json=removePeer,proto3,oneof"`
}

type Command_CompareAndSetAccountDetail struct {
	CompareAndSetAccountDetail *CompareAndSetAccountDetail `protobuf:"bytes,18,opt,name=compare_and_set_account_detail,json=compareAndSetAccountDetail,proto3,oneof"`
}

type Command_SetSettingValue struct {
	SetSettingValue *SetSettingValue `protobuf:"bytes,19,opt,name=set_setting_value,json=setSettingValue,proto3,oneof"`
}

type Command_CallEngine struct {
	CallEngine *CallEngine `protobuf:"bytes,20,opt,name=call_engine,json=callEngine,proto3,oneof"`
}

func (*Command_AddAssetQuantity) isCommand_Command() {}

func (*Command_AddPeer) isCommand_Command() {}

func (*Command_AddSignatory) isCommand_Command() {}

func (*Command_AppendRole) isCommand_Command() {}

func (*Command_CreateAccount) isCommand_Command() {}

func (*Command_CreateAsset) isCommand_Command() {}

func (*Command_CreateDomain) isCommand_Command() {}

func (*Command_CreateRole) isCommand_Command() {}

func (*Command_DetachRole) isCommand_Command() {}

func (*Command_GrantPermission) isCommand_Command() {}

func (*Command_RemoveSignatory) isCommand_Command() {}

func (*Command_RevokePermission) isCommand_Command() {}

func (*Command_SetAccountDetail) isCommand_Command() {}

func (*Command_SetAccountQuorum) isCommand_Command() {}

func (*Command_SubtractAssetQuantity) isCommand_Command() {}

func (*Command_TransferAsset) isCommand_Command() {}

func (*Command_RemovePeer) isCommand_Command() {}

func (*Command_CompareAndSetAccountDetail) isCommand_Command() {}

func (*Command_SetSettingValue) isCommand_Command() {}

func (*Command_CallEngine) isCommand_Command() {}

var File_commands_proto protoreflect.FileDescriptor

var file_commands_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x1a, 0x0f, 0x70, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x45, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x41, 0x73, 0x73, 0x65, 0x74, 0x51, 0x75, 0x61,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x73, 0x73, 0x65, 0x74, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x33, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x50,
	0x65, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x04, 0x70, 0x65, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x52, 0x04, 0x70, 0x65, 0x65, 0x72, 0x22, 0x2b, 0x0a,
	0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x65, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x4c, 0x0a, 0x0c, 0x41, 0x64,
	0x64, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x67, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x73, 0x73, 0x65, 0x74,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0x6e, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x22, 0x59, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4e, 0x0a, 0x0c,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x1b, 0x0a, 0x09,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x22, 0x4f, 0x0a, 0x0f,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x79, 0x12,
	0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x49, 0x0a,
	0x10, 0x53, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x51, 0x75, 0x6f, 0x72, 0x75,
	0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x22, 0xb2, 0x01, 0x0a, 0x0d, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x65, 0x72, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x72,
	0x63, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x73, 0x72, 0x63, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x26, 0x0a, 0x0f, 0x64, 0x65, 0x73, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x65, 0x73, 0x74, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x48, 0x0a,
	0x0a, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f,
	0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x48, 0x0a, 0x0a, 0x44, 0x65, 0x74, 0x61, 0x63,
	0x68, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x6b, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x40, 0x0a, 0x0b,
	0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0e, 0x32, 0x1e, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x75,
	0x0a, 0x0f, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x43, 0x0a, 0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x50,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x76, 0x0a, 0x10, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x50,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x43, 0x0a, 0x0a, 0x70, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x69,
	0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x47, 0x72,
	0x61, 0x6e, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x4a, 0x0a,
	0x15, 0x53, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x51, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x73, 0x73, 0x65, 0x74, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xb4, 0x01, 0x0a, 0x1a, 0x43, 0x6f,
	0x6d, 0x70, 0x61, 0x72, 0x65, 0x41, 0x6e, 0x64, 0x53, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x1d, 0x0a, 0x09, 0x6f, 0x6c, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x6f, 0x6c, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42,
	0x0f, 0x0a, 0x0d, 0x6f, 0x70, 0x74, 0x5f, 0x6f, 0x6c, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x39, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xaa, 0x01, 0x0a, 0x0a,
	0x43, 0x61, 0x6c, 0x6c, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x12, 0x39, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x45, 0x6e,
	0x67, 0x69, 0x6e, 0x65, 0x2e, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63,
	0x61, 0x6c, 0x6c, 0x65, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x22, 0x1b, 0x0a, 0x0a, 0x45,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x6b, 0x53, 0x6f,
	0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x10, 0x00, 0x22, 0xe6, 0x0b, 0x0a, 0x07, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x12, 0x50, 0x0a, 0x12, 0x61, 0x64, 0x64, 0x5f, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x5f, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x41, 0x64, 0x64, 0x41, 0x73, 0x73, 0x65, 0x74, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x48, 0x00, 0x52, 0x10, 0x61, 0x64, 0x64, 0x41, 0x73, 0x73, 0x65, 0x74, 0x51, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x34, 0x0a, 0x08, 0x61, 0x64, 0x64, 0x5f, 0x70, 0x65,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x65, 0x65,
	0x72, 0x48, 0x00, 0x52, 0x07, 0x61, 0x64, 0x64, 0x50, 0x65, 0x65, 0x72, 0x12, 0x43, 0x0a, 0x0d,
	0x61, 0x64, 0x64, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x6f, 0x72,
	0x79, 0x48, 0x00, 0x52, 0x0c, 0x61, 0x64, 0x64, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x6f, 0x72,
	0x79, 0x12, 0x3d, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x5f, 0x72, 0x6f, 0x6c, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x6f,
	0x6c, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x6f, 0x6c, 0x65,
	0x12, 0x46, 0x0a, 0x0e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x40, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x5f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x43, 0x0a, 0x0d, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x48,
	0x00, 0x52, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12,
	0x3d, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65,
	0x48, 0x00, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x3d,
	0x0a, 0x0b, 0x64, 0x65, 0x74, 0x61, 0x63, 0x68, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x63, 0x68, 0x52, 0x6f, 0x6c, 0x65, 0x48,
	0x00, 0x52, 0x0a, 0x64, 0x65, 0x74, 0x61, 0x63, 0x68, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x4c, 0x0a,
	0x10, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x5f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0f, 0x67, 0x72, 0x61, 0x6e,
	0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x4c, 0x0a, 0x10, 0x72,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x79, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x6f, 0x72, 0x79, 0x48, 0x00, 0x52, 0x0f, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x4f, 0x0a, 0x11, 0x72, 0x65, 0x76,
	0x6f, 0x6b, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x50, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x10, 0x72, 0x65, 0x76, 0x6f, 0x6b, 0x65,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x50, 0x0a, 0x12, 0x73, 0x65,
	0x74, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x48, 0x00, 0x52, 0x10, 0x73, 0x65, 0x74, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x50, 0x0a, 0x12,
	0x73, 0x65, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x71, 0x75, 0x6f, 0x72,
	0x75, 0x6d, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x48, 0x00, 0x52, 0x10, 0x73, 0x65,
	0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x51, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x12, 0x5f,
	0x0a, 0x17, 0x73, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x61, 0x73, 0x73, 0x65, 0x74,
	0x5f, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x25, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x53, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x51, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x48, 0x00, 0x52, 0x15, 0x73, 0x75, 0x62, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12,
	0x46, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x5f, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x41, 0x73, 0x73, 0x65, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x3d, 0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x5f, 0x70, 0x65, 0x65, 0x72, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x69,
	0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x50, 0x65, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x50, 0x65, 0x65, 0x72, 0x12, 0x70, 0x0a, 0x1e, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x72,
	0x65, 0x5f, 0x61, 0x6e, 0x64, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a,
	0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x41, 0x6e, 0x64, 0x53, 0x65, 0x74, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x48, 0x00, 0x52, 0x1a, 0x63, 0x6f,
	0x6d, 0x70, 0x61, 0x72, 0x65, 0x41, 0x6e, 0x64, 0x53, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x4d, 0x0a, 0x11, 0x73, 0x65, 0x74, 0x5f,
	0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x13, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x65, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x0f, 0x73, 0x65, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x3d, 0x0a, 0x0b, 0x63, 0x61, 0x6c, 0x6c, 0x5f,
	0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x69,
	0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x61,
	0x6c, 0x6c, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x61, 0x6c, 0x6c,
	0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x42, 0x1a, 0x5a, 0x18, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_commands_proto_rawDescOnce sync.Once
	file_commands_proto_rawDescData = file_commands_proto_rawDesc
)

func file_commands_proto_rawDescGZIP() []byte {
	file_commands_proto_rawDescOnce.Do(func() {
		file_commands_proto_rawDescData = protoimpl.X.CompressGZIP(file_commands_proto_rawDescData)
	})
	return file_commands_proto_rawDescData
}

var file_commands_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_commands_proto_goTypes = []interface{}{
	(CallEngine_EngineType)(0),         // 0: iroha.protocol.CallEngine.EngineType
	(*AddAssetQuantity)(nil),           // 1: iroha.protocol.AddAssetQuantity
	(*AddPeer)(nil),                    // 2: iroha.protocol.AddPeer
	(*RemovePeer)(nil),                 // 3: iroha.protocol.RemovePeer
	(*AddSignatory)(nil),               // 4: iroha.protocol.AddSignatory
	(*CreateAsset)(nil),                // 5: iroha.protocol.CreateAsset
	(*CreateAccount)(nil),              // 6: iroha.protocol.CreateAccount
	(*SetAccountDetail)(nil),           // 7: iroha.protocol.SetAccountDetail
	(*CreateDomain)(nil),               // 8: iroha.protocol.CreateDomain
	(*RemoveSignatory)(nil),            // 9: iroha.protocol.RemoveSignatory
	(*SetAccountQuorum)(nil),           // 10: iroha.protocol.SetAccountQuorum
	(*TransferAsset)(nil),              // 11: iroha.protocol.TransferAsset
	(*AppendRole)(nil),                 // 12: iroha.protocol.AppendRole
	(*DetachRole)(nil),                 // 13: iroha.protocol.DetachRole
	(*CreateRole)(nil),                 // 14: iroha.protocol.CreateRole
	(*GrantPermission)(nil),            // 15: iroha.protocol.GrantPermission
	(*RevokePermission)(nil),           // 16: iroha.protocol.RevokePermission
	(*SubtractAssetQuantity)(nil),      // 17: iroha.protocol.SubtractAssetQuantity
	(*CompareAndSetAccountDetail)(nil), // 18: iroha.protocol.CompareAndSetAccountDetail
	(*SetSettingValue)(nil),            // 19: iroha.protocol.SetSettingValue
	(*CallEngine)(nil),                 // 20: iroha.protocol.CallEngine
	(*Command)(nil),                    // 21: iroha.protocol.Command
	(*Peer)(nil),                       // 22: iroha.protocol.Peer
	(RolePermission)(0),                // 23: iroha.protocol.RolePermission
	(GrantablePermission)(0),           // 24: iroha.protocol.GrantablePermission
}
var file_commands_proto_depIdxs = []int32{
	22, // 0: iroha.protocol.AddPeer.peer:type_name -> iroha.protocol.Peer
	23, // 1: iroha.protocol.CreateRole.permissions:type_name -> iroha.protocol.RolePermission
	24, // 2: iroha.protocol.GrantPermission.permission:type_name -> iroha.protocol.GrantablePermission
	24, // 3: iroha.protocol.RevokePermission.permission:type_name -> iroha.protocol.GrantablePermission
	0,  // 4: iroha.protocol.CallEngine.type:type_name -> iroha.protocol.CallEngine.EngineType
	1,  // 5: iroha.protocol.Command.add_asset_quantity:type_name -> iroha.protocol.AddAssetQuantity
	2,  // 6: iroha.protocol.Command.add_peer:type_name -> iroha.protocol.AddPeer
	4,  // 7: iroha.protocol.Command.add_signatory:type_name -> iroha.protocol.AddSignatory
	12, // 8: iroha.protocol.Command.append_role:type_name -> iroha.protocol.AppendRole
	6,  // 9: iroha.protocol.Command.create_account:type_name -> iroha.protocol.CreateAccount
	5,  // 10: iroha.protocol.Command.create_asset:type_name -> iroha.protocol.CreateAsset
	8,  // 11: iroha.protocol.Command.create_domain:type_name -> iroha.protocol.CreateDomain
	14, // 12: iroha.protocol.Command.create_role:type_name -> iroha.protocol.CreateRole
	13, // 13: iroha.protocol.Command.detach_role:type_name -> iroha.protocol.DetachRole
	15, // 14: iroha.protocol.Command.grant_permission:type_name -> iroha.protocol.GrantPermission
	9,  // 15: iroha.protocol.Command.remove_signatory:type_name -> iroha.protocol.RemoveSignatory
	16, // 16: iroha.protocol.Command.revoke_permission:type_name -> iroha.protocol.RevokePermission
	7,  // 17: iroha.protocol.Command.set_account_detail:type_name -> iroha.protocol.SetAccountDetail
	10, // 18: iroha.protocol.Command.set_account_quorum:type_name -> iroha.protocol.SetAccountQuorum
	17, // 19: iroha.protocol.Command.subtract_asset_quantity:type_name -> iroha.protocol.SubtractAssetQuantity
	11, // 20: iroha.protocol.Command.transfer_asset:type_name -> iroha.protocol.TransferAsset
	3,  // 21: iroha.protocol.Command.remove_peer:type_name -> iroha.protocol.RemovePeer
	18, // 22: iroha.protocol.Command.compare_and_set_account_detail:type_name -> iroha.protocol.CompareAndSetAccountDetail
	19, // 23: iroha.protocol.Command.set_setting_value:type_name -> iroha.protocol.SetSettingValue
	20, // 24: iroha.protocol.Command.call_engine:type_name -> iroha.protocol.CallEngine
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_commands_proto_init() }
func file_commands_proto_init() {
	if File_commands_proto != nil {
		return
	}
	file_primitive_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_commands_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddAssetQuantity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commands_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPeer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commands_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemovePeer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commands_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSignatory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commands_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAsset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commands_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commands_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetAccountDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commands_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDomain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commands_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveSignatory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commands_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetAccountQuorum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commands_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferAsset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commands_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppendRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commands_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetachRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commands_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commands_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrantPermission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commands_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevokePermission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commands_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubtractAssetQuantity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commands_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompareAndSetAccountDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commands_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSettingValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commands_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallEngine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_commands_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_commands_proto_msgTypes[17].OneofWrappers = []interface{}{
		(*CompareAndSetAccountDetail_OldValue)(nil),
	}
	file_commands_proto_msgTypes[20].OneofWrappers = []interface{}{
		(*Command_AddAssetQuantity)(nil),
		(*Command_AddPeer)(nil),
		(*Command_AddSignatory)(nil),
		(*Command_AppendRole)(nil),
		(*Command_CreateAccount)(nil),
		(*Command_CreateAsset)(nil),
		(*Command_CreateDomain)(nil),
		(*Command_CreateRole)(nil),
		(*Command_DetachRole)(nil),
		(*Command_GrantPermission)(nil),
		(*Command_RemoveSignatory)(nil),
		(*Command_RevokePermission)(nil),
		(*Command_SetAccountDetail)(nil),
		(*Command_SetAccountQuorum)(nil),
		(*Command_SubtractAssetQuantity)(nil),
		(*Command_TransferAsset)(nil),
		(*Command_RemovePeer)(nil),
		(*Command_CompareAndSetAccountDetail)(nil),
		(*Command_SetSettingValue)(nil),
		(*Command_CallEngine)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_commands_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commands_proto_goTypes,
		DependencyIndexes: file_commands_proto_depIdxs,
		EnumInfos:         file_commands_proto_enumTypes,
		MessageInfos:      file_commands_proto_msgTypes,
	}.Build()
	File_commands_proto = out.File
	file_commands_proto_rawDesc = nil
	file_commands_proto_goTypes = nil
	file_commands_proto_depIdxs = nil
}
