//*
// Copyright Soramitsu Co., Ltd. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.11.2
// source: qry_responses.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorResponse_Reason int32

const (
	ErrorResponse_STATELESS_INVALID ErrorResponse_Reason = 0
	ErrorResponse_STATEFUL_INVALID  ErrorResponse_Reason = 1
	ErrorResponse_NO_ACCOUNT        ErrorResponse_Reason = 2 // when requested account does not exist
	ErrorResponse_NO_ACCOUNT_ASSETS ErrorResponse_Reason = 3 // when requested account asset does not exist
	ErrorResponse_NO_ACCOUNT_DETAIL ErrorResponse_Reason = 4 // when requested account detail does not exist
	ErrorResponse_NO_SIGNATORIES    ErrorResponse_Reason = 5 // when requested signatories does not exist
	ErrorResponse_NOT_SUPPORTED     ErrorResponse_Reason = 6 // when unidentified request was received
	ErrorResponse_NO_ASSET          ErrorResponse_Reason = 7 // when requested asset does not exist
	ErrorResponse_NO_ROLES          ErrorResponse_Reason = 8 // when there are no roles defined in the system
)

// Enum value maps for ErrorResponse_Reason.
var (
	ErrorResponse_Reason_name = map[int32]string{
		0: "STATELESS_INVALID",
		1: "STATEFUL_INVALID",
		2: "NO_ACCOUNT",
		3: "NO_ACCOUNT_ASSETS",
		4: "NO_ACCOUNT_DETAIL",
		5: "NO_SIGNATORIES",
		6: "NOT_SUPPORTED",
		7: "NO_ASSET",
		8: "NO_ROLES",
	}
	ErrorResponse_Reason_value = map[string]int32{
		"STATELESS_INVALID": 0,
		"STATEFUL_INVALID":  1,
		"NO_ACCOUNT":        2,
		"NO_ACCOUNT_ASSETS": 3,
		"NO_ACCOUNT_DETAIL": 4,
		"NO_SIGNATORIES":    5,
		"NOT_SUPPORTED":     6,
		"NO_ASSET":          7,
		"NO_ROLES":          8,
	}
)

func (x ErrorResponse_Reason) Enum() *ErrorResponse_Reason {
	p := new(ErrorResponse_Reason)
	*p = x
	return p
}

func (x ErrorResponse_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorResponse_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_qry_responses_proto_enumTypes[0].Descriptor()
}

func (ErrorResponse_Reason) Type() protoreflect.EnumType {
	return &file_qry_responses_proto_enumTypes[0]
}

func (x ErrorResponse_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorResponse_Reason.Descriptor instead.
func (ErrorResponse_Reason) EnumDescriptor() ([]byte, []int) {
	return file_qry_responses_proto_rawDescGZIP(), []int{10, 0}
}

// *** WSV data structure *** //
type Asset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetId   string `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	DomainId  string `protobuf:"bytes,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	Precision uint32 `protobuf:"varint,3,opt,name=precision,proto3" json:"precision,omitempty"`
}

func (x *Asset) Reset() {
	*x = Asset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qry_responses_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_qry_responses_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_qry_responses_proto_rawDescGZIP(), []int{0}
}

func (x *Asset) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *Asset) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

func (x *Asset) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

type Domain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DomainId    string `protobuf:"bytes,1,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	DefaultRole string `protobuf:"bytes,2,opt,name=default_role,json=defaultRole,proto3" json:"default_role,omitempty"`
}

func (x *Domain) Reset() {
	*x = Domain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qry_responses_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain) ProtoMessage() {}

func (x *Domain) ProtoReflect() protoreflect.Message {
	mi := &file_qry_responses_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain.ProtoReflect.Descriptor instead.
func (*Domain) Descriptor() ([]byte, []int) {
	return file_qry_responses_proto_rawDescGZIP(), []int{1}
}

func (x *Domain) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

func (x *Domain) GetDefaultRole() string {
	if x != nil {
		return x.DefaultRole
	}
	return ""
}

type Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	DomainId  string `protobuf:"bytes,2,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	Quorum    uint32 `protobuf:"varint,3,opt,name=quorum,proto3" json:"quorum,omitempty"`
	JsonData  string `protobuf:"bytes,4,opt,name=json_data,json=jsonData,proto3" json:"json_data,omitempty"`
}

func (x *Account) Reset() {
	*x = Account{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qry_responses_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_qry_responses_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_qry_responses_proto_rawDescGZIP(), []int{2}
}

func (x *Account) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Account) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

func (x *Account) GetQuorum() uint32 {
	if x != nil {
		return x.Quorum
	}
	return 0
}

func (x *Account) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

type AccountAsset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetId   string `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Balance   string `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (x *AccountAsset) Reset() {
	*x = AccountAsset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qry_responses_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountAsset) ProtoMessage() {}

func (x *AccountAsset) ProtoReflect() protoreflect.Message {
	mi := &file_qry_responses_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountAsset.ProtoReflect.Descriptor instead.
func (*AccountAsset) Descriptor() ([]byte, []int) {
	return file_qry_responses_proto_rawDescGZIP(), []int{3}
}

func (x *AccountAsset) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *AccountAsset) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountAsset) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

// *** Responses *** //
type AccountAssetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountAssets []*AccountAsset `protobuf:"bytes,1,rep,name=account_assets,json=accountAssets,proto3" json:"account_assets,omitempty"`
	TotalNumber   uint32          `protobuf:"varint,2,opt,name=total_number,json=totalNumber,proto3" json:"total_number,omitempty"`
	// Types that are assignable to OptNextAssetId:
	//	*AccountAssetResponse_NextAssetId
	OptNextAssetId isAccountAssetResponse_OptNextAssetId `protobuf_oneof:"opt_next_asset_id"`
}

func (x *AccountAssetResponse) Reset() {
	*x = AccountAssetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qry_responses_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountAssetResponse) ProtoMessage() {}

func (x *AccountAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qry_responses_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountAssetResponse.ProtoReflect.Descriptor instead.
func (*AccountAssetResponse) Descriptor() ([]byte, []int) {
	return file_qry_responses_proto_rawDescGZIP(), []int{4}
}

func (x *AccountAssetResponse) GetAccountAssets() []*AccountAsset {
	if x != nil {
		return x.AccountAssets
	}
	return nil
}

func (x *AccountAssetResponse) GetTotalNumber() uint32 {
	if x != nil {
		return x.TotalNumber
	}
	return 0
}

func (m *AccountAssetResponse) GetOptNextAssetId() isAccountAssetResponse_OptNextAssetId {
	if m != nil {
		return m.OptNextAssetId
	}
	return nil
}

func (x *AccountAssetResponse) GetNextAssetId() string {
	if x, ok := x.GetOptNextAssetId().(*AccountAssetResponse_NextAssetId); ok {
		return x.NextAssetId
	}
	return ""
}

type isAccountAssetResponse_OptNextAssetId interface {
	isAccountAssetResponse_OptNextAssetId()
}

type AccountAssetResponse_NextAssetId struct {
	NextAssetId string `protobuf:"bytes,3,opt,name=next_asset_id,json=nextAssetId,proto3,oneof"`
}

func (*AccountAssetResponse_NextAssetId) isAccountAssetResponse_OptNextAssetId() {}

type AccountDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Detail       string                 `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	TotalNumber  uint64                 `protobuf:"varint,2,opt,name=total_number,json=totalNumber,proto3" json:"total_number,omitempty"`
	NextRecordId *AccountDetailRecordId `protobuf:"bytes,3,opt,name=next_record_id,json=nextRecordId,proto3" json:"next_record_id,omitempty"`
}

func (x *AccountDetailResponse) Reset() {
	*x = AccountDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qry_responses_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountDetailResponse) ProtoMessage() {}

func (x *AccountDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qry_responses_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountDetailResponse.ProtoReflect.Descriptor instead.
func (*AccountDetailResponse) Descriptor() ([]byte, []int) {
	return file_qry_responses_proto_rawDescGZIP(), []int{5}
}

func (x *AccountDetailResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *AccountDetailResponse) GetTotalNumber() uint64 {
	if x != nil {
		return x.TotalNumber
	}
	return 0
}

func (x *AccountDetailResponse) GetNextRecordId() *AccountDetailRecordId {
	if x != nil {
		return x.NextRecordId
	}
	return nil
}

type AccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account      *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	AccountRoles []string `protobuf:"bytes,2,rep,name=account_roles,json=accountRoles,proto3" json:"account_roles,omitempty"`
}

func (x *AccountResponse) Reset() {
	*x = AccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qry_responses_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountResponse) ProtoMessage() {}

func (x *AccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qry_responses_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountResponse.ProtoReflect.Descriptor instead.
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return file_qry_responses_proto_rawDescGZIP(), []int{6}
}

func (x *AccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *AccountResponse) GetAccountRoles() []string {
	if x != nil {
		return x.AccountRoles
	}
	return nil
}

type AssetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Asset *Asset `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
}

func (x *AssetResponse) Reset() {
	*x = AssetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qry_responses_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetResponse) ProtoMessage() {}

func (x *AssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qry_responses_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetResponse.ProtoReflect.Descriptor instead.
func (*AssetResponse) Descriptor() ([]byte, []int) {
	return file_qry_responses_proto_rawDescGZIP(), []int{7}
}

func (x *AssetResponse) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

type RolesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roles []string `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
}

func (x *RolesResponse) Reset() {
	*x = RolesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qry_responses_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolesResponse) ProtoMessage() {}

func (x *RolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qry_responses_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolesResponse.ProtoReflect.Descriptor instead.
func (*RolesResponse) Descriptor() ([]byte, []int) {
	return file_qry_responses_proto_rawDescGZIP(), []int{8}
}

func (x *RolesResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type RolePermissionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Permissions []RolePermission `protobuf:"varint,1,rep,packed,name=permissions,proto3,enum=iroha.protocol.RolePermission" json:"permissions,omitempty"`
}

func (x *RolePermissionsResponse) Reset() {
	*x = RolePermissionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qry_responses_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolePermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissionsResponse) ProtoMessage() {}

func (x *RolePermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qry_responses_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissionsResponse.ProtoReflect.Descriptor instead.
func (*RolePermissionsResponse) Descriptor() ([]byte, []int) {
	return file_qry_responses_proto_rawDescGZIP(), []int{9}
}

func (x *RolePermissionsResponse) GetPermissions() []RolePermission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type ErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason    ErrorResponse_Reason `protobuf:"varint,1,opt,name=reason,proto3,enum=iroha.protocol.ErrorResponse_Reason" json:"reason,omitempty"`
	Message   string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode uint32               `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qry_responses_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qry_responses_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_qry_responses_proto_rawDescGZIP(), []int{10}
}

func (x *ErrorResponse) GetReason() ErrorResponse_Reason {
	if x != nil {
		return x.Reason
	}
	return ErrorResponse_STATELESS_INVALID
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetErrorCode() uint32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

type SignatoriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *SignatoriesResponse) Reset() {
	*x = SignatoriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qry_responses_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignatoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatoriesResponse) ProtoMessage() {}

func (x *SignatoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qry_responses_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatoriesResponse.ProtoReflect.Descriptor instead.
func (*SignatoriesResponse) Descriptor() ([]byte, []int) {
	return file_qry_responses_proto_rawDescGZIP(), []int{11}
}

func (x *SignatoriesResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type TransactionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transactions []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
}

func (x *TransactionsResponse) Reset() {
	*x = TransactionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qry_responses_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionsResponse) ProtoMessage() {}

func (x *TransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qry_responses_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionsResponse.ProtoReflect.Descriptor instead.
func (*TransactionsResponse) Descriptor() ([]byte, []int) {
	return file_qry_responses_proto_rawDescGZIP(), []int{12}
}

func (x *TransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type TransactionsPageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transactions        []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	AllTransactionsSize uint32         `protobuf:"varint,2,opt,name=all_transactions_size,json=allTransactionsSize,proto3" json:"all_transactions_size,omitempty"`
	// Types that are assignable to NextPageTag:
	//	*TransactionsPageResponse_NextTxHash
	NextPageTag isTransactionsPageResponse_NextPageTag `protobuf_oneof:"next_page_tag"`
}

func (x *TransactionsPageResponse) Reset() {
	*x = TransactionsPageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qry_responses_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionsPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionsPageResponse) ProtoMessage() {}

func (x *TransactionsPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qry_responses_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionsPageResponse.ProtoReflect.Descriptor instead.
func (*TransactionsPageResponse) Descriptor() ([]byte, []int) {
	return file_qry_responses_proto_rawDescGZIP(), []int{13}
}

func (x *TransactionsPageResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *TransactionsPageResponse) GetAllTransactionsSize() uint32 {
	if x != nil {
		return x.AllTransactionsSize
	}
	return 0
}

func (m *TransactionsPageResponse) GetNextPageTag() isTransactionsPageResponse_NextPageTag {
	if m != nil {
		return m.NextPageTag
	}
	return nil
}

func (x *TransactionsPageResponse) GetNextTxHash() string {
	if x, ok := x.GetNextPageTag().(*TransactionsPageResponse_NextTxHash); ok {
		return x.NextTxHash
	}
	return ""
}

type isTransactionsPageResponse_NextPageTag interface {
	isTransactionsPageResponse_NextPageTag()
}

type TransactionsPageResponse_NextTxHash struct {
	NextTxHash string `protobuf:"bytes,3,opt,name=next_tx_hash,json=nextTxHash,proto3,oneof"`
}

func (*TransactionsPageResponse_NextTxHash) isTransactionsPageResponse_NextPageTag() {}

type PendingTransactionsPageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transactions        []*Transaction                             `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	AllTransactionsSize uint32                                     `protobuf:"varint,2,opt,name=all_transactions_size,json=allTransactionsSize,proto3" json:"all_transactions_size,omitempty"`
	NextBatchInfo       *PendingTransactionsPageResponse_BatchInfo `protobuf:"bytes,3,opt,name=next_batch_info,json=nextBatchInfo,proto3" json:"next_batch_info,omitempty"`
}

func (x *PendingTransactionsPageResponse) Reset() {
	*x = PendingTransactionsPageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qry_responses_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PendingTransactionsPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingTransactionsPageResponse) ProtoMessage() {}

func (x *PendingTransactionsPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qry_responses_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingTransactionsPageResponse.ProtoReflect.Descriptor instead.
func (*PendingTransactionsPageResponse) Descriptor() ([]byte, []int) {
	return file_qry_responses_proto_rawDescGZIP(), []int{14}
}

func (x *PendingTransactionsPageResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *PendingTransactionsPageResponse) GetAllTransactionsSize() uint32 {
	if x != nil {
		return x.AllTransactionsSize
	}
	return 0
}

func (x *PendingTransactionsPageResponse) GetNextBatchInfo() *PendingTransactionsPageResponse_BatchInfo {
	if x != nil {
		return x.NextBatchInfo
	}
	return nil
}

type PeersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peers []*Peer `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
}

func (x *PeersResponse) Reset() {
	*x = PeersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qry_responses_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersResponse) ProtoMessage() {}

func (x *PeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qry_responses_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersResponse.ProtoReflect.Descriptor instead.
func (*PeersResponse) Descriptor() ([]byte, []int) {
	return file_qry_responses_proto_rawDescGZIP(), []int{15}
}

func (x *PeersResponse) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type EngineReceiptsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EngineReceipts []*EngineReceipt `protobuf:"bytes,1,rep,name=engine_receipts,json=engineReceipts,proto3" json:"engine_receipts,omitempty"`
}

func (x *EngineReceiptsResponse) Reset() {
	*x = EngineReceiptsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qry_responses_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EngineReceiptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineReceiptsResponse) ProtoMessage() {}

func (x *EngineReceiptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qry_responses_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineReceiptsResponse.ProtoReflect.Descriptor instead.
func (*EngineReceiptsResponse) Descriptor() ([]byte, []int) {
	return file_qry_responses_proto_rawDescGZIP(), []int{16}
}

func (x *EngineReceiptsResponse) GetEngineReceipts() []*EngineReceipt {
	if x != nil {
		return x.EngineReceipts
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*QueryResponse_AccountAssetsResponse
	//	*QueryResponse_AccountDetailResponse
	//	*QueryResponse_AccountResponse
	//	*QueryResponse_ErrorResponse
	//	*QueryResponse_SignatoriesResponse
	//	*QueryResponse_TransactionsResponse
	//	*QueryResponse_AssetResponse
	//	*QueryResponse_RolesResponse
	//	*QueryResponse_RolePermissionsResponse
	//	*QueryResponse_TransactionsPageResponse
	//	*QueryResponse_PendingTransactionsPageResponse
	//	*QueryResponse_BlockResponse
	//	*QueryResponse_PeersResponse
	//	*QueryResponse_EngineReceiptsResponse
	Response  isQueryResponse_Response `protobuf_oneof:"response"`
	QueryHash string                   `protobuf:"bytes,10,opt,name=query_hash,json=queryHash,proto3" json:"query_hash,omitempty"`
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qry_responses_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qry_responses_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_qry_responses_proto_rawDescGZIP(), []int{17}
}

func (m *QueryResponse) GetResponse() isQueryResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *QueryResponse) GetAccountAssetsResponse() *AccountAssetResponse {
	if x, ok := x.GetResponse().(*QueryResponse_AccountAssetsResponse); ok {
		return x.AccountAssetsResponse
	}
	return nil
}

func (x *QueryResponse) GetAccountDetailResponse() *AccountDetailResponse {
	if x, ok := x.GetResponse().(*QueryResponse_AccountDetailResponse); ok {
		return x.AccountDetailResponse
	}
	return nil
}

func (x *QueryResponse) GetAccountResponse() *AccountResponse {
	if x, ok := x.GetResponse().(*QueryResponse_AccountResponse); ok {
		return x.AccountResponse
	}
	return nil
}

func (x *QueryResponse) GetErrorResponse() *ErrorResponse {
	if x, ok := x.GetResponse().(*QueryResponse_ErrorResponse); ok {
		return x.ErrorResponse
	}
	return nil
}

func (x *QueryResponse) GetSignatoriesResponse() *SignatoriesResponse {
	if x, ok := x.GetResponse().(*QueryResponse_SignatoriesResponse); ok {
		return x.SignatoriesResponse
	}
	return nil
}

func (x *QueryResponse) GetTransactionsResponse() *TransactionsResponse {
	if x, ok := x.GetResponse().(*QueryResponse_TransactionsResponse); ok {
		return x.TransactionsResponse
	}
	return nil
}

func (x *QueryResponse) GetAssetResponse() *AssetResponse {
	if x, ok := x.GetResponse().(*QueryResponse_AssetResponse); ok {
		return x.AssetResponse
	}
	return nil
}

func (x *QueryResponse) GetRolesResponse() *RolesResponse {
	if x, ok := x.GetResponse().(*QueryResponse_RolesResponse); ok {
		return x.RolesResponse
	}
	return nil
}

func (x *QueryResponse) GetRolePermissionsResponse() *RolePermissionsResponse {
	if x, ok := x.GetResponse().(*QueryResponse_RolePermissionsResponse); ok {
		return x.RolePermissionsResponse
	}
	return nil
}

func (x *QueryResponse) GetTransactionsPageResponse() *TransactionsPageResponse {
	if x, ok := x.GetResponse().(*QueryResponse_TransactionsPageResponse); ok {
		return x.TransactionsPageResponse
	}
	return nil
}

func (x *QueryResponse) GetPendingTransactionsPageResponse() *PendingTransactionsPageResponse {
	if x, ok := x.GetResponse().(*QueryResponse_PendingTransactionsPageResponse); ok {
		return x.PendingTransactionsPageResponse
	}
	return nil
}

func (x *QueryResponse) GetBlockResponse() *BlockResponse {
	if x, ok := x.GetResponse().(*QueryResponse_BlockResponse); ok {
		return x.BlockResponse
	}
	return nil
}

func (x *QueryResponse) GetPeersResponse() *PeersResponse {
	if x, ok := x.GetResponse().(*QueryResponse_PeersResponse); ok {
		return x.PeersResponse
	}
	return nil
}

func (x *QueryResponse) GetEngineReceiptsResponse() *EngineReceiptsResponse {
	if x, ok := x.GetResponse().(*QueryResponse_EngineReceiptsResponse); ok {
		return x.EngineReceiptsResponse
	}
	return nil
}

func (x *QueryResponse) GetQueryHash() string {
	if x != nil {
		return x.QueryHash
	}
	return ""
}

type isQueryResponse_Response interface {
	isQueryResponse_Response()
}

type QueryResponse_AccountAssetsResponse struct {
	AccountAssetsResponse *AccountAssetResponse `protobuf:"bytes,1,opt,name=account_assets_response,json=accountAssetsResponse,proto3,oneof"`
}

type QueryResponse_AccountDetailResponse struct {
	AccountDetailResponse *AccountDetailResponse `protobuf:"bytes,2,opt,name=account_detail_response,json=accountDetailResponse,proto3,oneof"`
}

type QueryResponse_AccountResponse struct {
	AccountResponse *AccountResponse `protobuf:"bytes,3,opt,name=account_response,json=accountResponse,proto3,oneof"`
}

type QueryResponse_ErrorResponse struct {
	ErrorResponse *ErrorResponse `protobuf:"bytes,4,opt,name=error_response,json=errorResponse,proto3,oneof"`
}

type QueryResponse_SignatoriesResponse struct {
	SignatoriesResponse *SignatoriesResponse `protobuf:"bytes,5,opt,name=signatories_response,json=signatoriesResponse,proto3,oneof"`
}

type QueryResponse_TransactionsResponse struct {
	TransactionsResponse *TransactionsResponse `protobuf:"bytes,6,opt,name=transactions_response,json=transactionsResponse,proto3,oneof"`
}

type QueryResponse_AssetResponse struct {
	AssetResponse *AssetResponse `protobuf:"bytes,7,opt,name=asset_response,json=assetResponse,proto3,oneof"`
}

type QueryResponse_RolesResponse struct {
	RolesResponse *RolesResponse `protobuf:"bytes,8,opt,name=roles_response,json=rolesResponse,proto3,oneof"`
}

type QueryResponse_RolePermissionsResponse struct {
	RolePermissionsResponse *RolePermissionsResponse `protobuf:"bytes,9,opt,name=role_permissions_response,json=rolePermissionsResponse,proto3,oneof"`
}

type QueryResponse_TransactionsPageResponse struct {
	TransactionsPageResponse *TransactionsPageResponse `protobuf:"bytes,11,opt,name=transactions_page_response,json=transactionsPageResponse,proto3,oneof"`
}

type QueryResponse_PendingTransactionsPageResponse struct {
	PendingTransactionsPageResponse *PendingTransactionsPageResponse `protobuf:"bytes,13,opt,name=pending_transactions_page_response,json=pendingTransactionsPageResponse,proto3,oneof"`
}

type QueryResponse_BlockResponse struct {
	BlockResponse *BlockResponse `protobuf:"bytes,12,opt,name=block_response,json=blockResponse,proto3,oneof"`
}

type QueryResponse_PeersResponse struct {
	PeersResponse *PeersResponse `protobuf:"bytes,14,opt,name=peers_response,json=peersResponse,proto3,oneof"`
}

type QueryResponse_EngineReceiptsResponse struct {
	EngineReceiptsResponse *EngineReceiptsResponse `protobuf:"bytes,15,opt,name=engine_receipts_response,json=engineReceiptsResponse,proto3,oneof"`
}

func (*QueryResponse_AccountAssetsResponse) isQueryResponse_Response() {}

func (*QueryResponse_AccountDetailResponse) isQueryResponse_Response() {}

func (*QueryResponse_AccountResponse) isQueryResponse_Response() {}

func (*QueryResponse_ErrorResponse) isQueryResponse_Response() {}

func (*QueryResponse_SignatoriesResponse) isQueryResponse_Response() {}

func (*QueryResponse_TransactionsResponse) isQueryResponse_Response() {}

func (*QueryResponse_AssetResponse) isQueryResponse_Response() {}

func (*QueryResponse_RolesResponse) isQueryResponse_Response() {}

func (*QueryResponse_RolePermissionsResponse) isQueryResponse_Response() {}

func (*QueryResponse_TransactionsPageResponse) isQueryResponse_Response() {}

func (*QueryResponse_PendingTransactionsPageResponse) isQueryResponse_Response() {}

func (*QueryResponse_BlockResponse) isQueryResponse_Response() {}

func (*QueryResponse_PeersResponse) isQueryResponse_Response() {}

func (*QueryResponse_EngineReceiptsResponse) isQueryResponse_Response() {}

type BlockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block *Block `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
}

func (x *BlockResponse) Reset() {
	*x = BlockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qry_responses_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockResponse) ProtoMessage() {}

func (x *BlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qry_responses_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockResponse.ProtoReflect.Descriptor instead.
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return file_qry_responses_proto_rawDescGZIP(), []int{18}
}

func (x *BlockResponse) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

type BlockErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BlockErrorResponse) Reset() {
	*x = BlockErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qry_responses_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockErrorResponse) ProtoMessage() {}

func (x *BlockErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qry_responses_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockErrorResponse.ProtoReflect.Descriptor instead.
func (*BlockErrorResponse) Descriptor() ([]byte, []int) {
	return file_qry_responses_proto_rawDescGZIP(), []int{19}
}

func (x *BlockErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BlockQueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*BlockQueryResponse_BlockResponse
	//	*BlockQueryResponse_BlockErrorResponse
	Response isBlockQueryResponse_Response `protobuf_oneof:"response"`
}

func (x *BlockQueryResponse) Reset() {
	*x = BlockQueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qry_responses_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockQueryResponse) ProtoMessage() {}

func (x *BlockQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qry_responses_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockQueryResponse.ProtoReflect.Descriptor instead.
func (*BlockQueryResponse) Descriptor() ([]byte, []int) {
	return file_qry_responses_proto_rawDescGZIP(), []int{20}
}

func (m *BlockQueryResponse) GetResponse() isBlockQueryResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *BlockQueryResponse) GetBlockResponse() *BlockResponse {
	if x, ok := x.GetResponse().(*BlockQueryResponse_BlockResponse); ok {
		return x.BlockResponse
	}
	return nil
}

func (x *BlockQueryResponse) GetBlockErrorResponse() *BlockErrorResponse {
	if x, ok := x.GetResponse().(*BlockQueryResponse_BlockErrorResponse); ok {
		return x.BlockErrorResponse
	}
	return nil
}

type isBlockQueryResponse_Response interface {
	isBlockQueryResponse_Response()
}

type BlockQueryResponse_BlockResponse struct {
	BlockResponse *BlockResponse `protobuf:"bytes,1,opt,name=block_response,json=blockResponse,proto3,oneof"`
}

type BlockQueryResponse_BlockErrorResponse struct {
	BlockErrorResponse *BlockErrorResponse `protobuf:"bytes,2,opt,name=block_error_response,json=blockErrorResponse,proto3,oneof"`
}

func (*BlockQueryResponse_BlockResponse) isBlockQueryResponse_Response() {}

func (*BlockQueryResponse_BlockErrorResponse) isBlockQueryResponse_Response() {}

type PendingTransactionsPageResponse_BatchInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstTxHash string `protobuf:"bytes,1,opt,name=first_tx_hash,json=firstTxHash,proto3" json:"first_tx_hash,omitempty"`
	BatchSize   uint32 `protobuf:"varint,2,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
}

func (x *PendingTransactionsPageResponse_BatchInfo) Reset() {
	*x = PendingTransactionsPageResponse_BatchInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qry_responses_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PendingTransactionsPageResponse_BatchInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingTransactionsPageResponse_BatchInfo) ProtoMessage() {}

func (x *PendingTransactionsPageResponse_BatchInfo) ProtoReflect() protoreflect.Message {
	mi := &file_qry_responses_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingTransactionsPageResponse_BatchInfo.ProtoReflect.Descriptor instead.
func (*PendingTransactionsPageResponse_BatchInfo) Descriptor() ([]byte, []int) {
	return file_qry_responses_proto_rawDescGZIP(), []int{14, 0}
}

func (x *PendingTransactionsPageResponse_BatchInfo) GetFirstTxHash() string {
	if x != nil {
		return x.FirstTxHash
	}
	return ""
}

func (x *PendingTransactionsPageResponse_BatchInfo) GetBatchSize() uint32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

var File_qry_responses_proto protoreflect.FileDescriptor

var file_qry_responses_proto_rawDesc = []byte{
	0x0a, 0x13, 0x71, 0x72, 0x79, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x11, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x70, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x05, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x65, 0x63,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x48, 0x0a, 0x06, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12,
	0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x22,
	0x7a, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x12, 0x1b,
	0x0a, 0x09, 0x6a, 0x73, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6a, 0x73, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x22, 0x62, 0x0a, 0x0c, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22,
	0xb9, 0x01, 0x0a, 0x14, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0e, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x0d,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x12, 0x21, 0x0a,
	0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x24, 0x0a, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x6e, 0x65, 0x78, 0x74, 0x41,
	0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x42, 0x13, 0x0a, 0x11, 0x6f, 0x70, 0x74, 0x5f, 0x6e, 0x65,
	0x78, 0x74, 0x5f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x22, 0x9f, 0x01, 0x0a, 0x15,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x21, 0x0a,
	0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x4b, 0x0a, 0x0e, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x52,
	0x0c, 0x6e, 0x65, 0x78, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x22, 0x69, 0x0a,
	0x0f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x31, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x72,
	0x6f, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x3c, 0x0a, 0x0d, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52,
	0x05, 0x61, 0x73, 0x73, 0x65, 0x74, 0x22, 0x25, 0x0a, 0x0d, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x5b, 0x0a,
	0x17, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x1e, 0x2e,
	0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x52,
	0x6f, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x70,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xbf, 0x02, 0x0a, 0x0d, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x69,
	0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x22, 0xb6, 0x01, 0x0a, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x15,
	0x0a, 0x11, 0x53, 0x54, 0x41, 0x54, 0x45, 0x4c, 0x45, 0x53, 0x53, 0x5f, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x54, 0x41, 0x54, 0x45, 0x46, 0x55,
	0x4c, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x4e,
	0x4f, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x4e,
	0x4f, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x41, 0x53, 0x53, 0x45, 0x54, 0x53,
	0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x4e, 0x4f, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54,
	0x5f, 0x44, 0x45, 0x54, 0x41, 0x49, 0x4c, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x4e, 0x4f, 0x5f,
	0x53, 0x49, 0x47, 0x4e, 0x41, 0x54, 0x4f, 0x52, 0x49, 0x45, 0x53, 0x10, 0x05, 0x12, 0x11, 0x0a,
	0x0d, 0x4e, 0x4f, 0x54, 0x5f, 0x53, 0x55, 0x50, 0x50, 0x4f, 0x52, 0x54, 0x45, 0x44, 0x10, 0x06,
	0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x5f, 0x41, 0x53, 0x53, 0x45, 0x54, 0x10, 0x07, 0x12, 0x0c,
	0x0a, 0x08, 0x4e, 0x4f, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x53, 0x10, 0x08, 0x22, 0x29, 0x0a, 0x13,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x57, 0x0a, 0x14, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3f, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x22, 0xc4, 0x01, 0x0a, 0x18, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a,
	0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x32,
	0x0a, 0x15, 0x61, 0x6c, 0x6c, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x13, 0x61,
	0x6c, 0x6c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x53, 0x69,
	0x7a, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x74, 0x78, 0x5f, 0x68, 0x61,
	0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x6e, 0x65, 0x78, 0x74,
	0x54, 0x78, 0x48, 0x61, 0x73, 0x68, 0x42, 0x0f, 0x0a, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70,
	0x61, 0x67, 0x65, 0x5f, 0x74, 0x61, 0x67, 0x22, 0xc9, 0x02, 0x0a, 0x1f, 0x50, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x50,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0c, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x32, 0x0a, 0x15,
	0x61, 0x6c, 0x6c, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x13, 0x61, 0x6c, 0x6c,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x61, 0x0a, 0x0f, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x69, 0x72, 0x6f, 0x68,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x50, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x49,
	0x6e, 0x66, 0x6f, 0x1a, 0x4e, 0x0a, 0x09, 0x42, 0x61, 0x74, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x22, 0x0a, 0x0d, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x74, 0x78, 0x5f, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x69, 0x72, 0x73, 0x74, 0x54, 0x78,
	0x48, 0x61, 0x73, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x62, 0x61, 0x74, 0x63, 0x68, 0x53,
	0x69, 0x7a, 0x65, 0x22, 0x3b, 0x0a, 0x0d, 0x50, 0x65, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x52, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73,
	0x22, 0x60, 0x0a, 0x16, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0f, 0x65, 0x6e,
	0x67, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x70, 0x74, 0x52, 0x0e, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70,
	0x74, 0x73, 0x22, 0x9d, 0x0a, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x17, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x15, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5f, 0x0a, 0x17, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x15,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x10, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x00, 0x52, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x69, 0x72,
	0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x14, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x69, 0x72, 0x6f, 0x68,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00,
	0x52, 0x13, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a, 0x15, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x14, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x46, 0x0a, 0x0e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x69, 0x72, 0x6f,
	0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0e, 0x72, 0x6f,
	0x6c, 0x65, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x65, 0x0a, 0x19, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00,
	0x52, 0x17, 0x72, 0x6f, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a, 0x1a, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e,
	0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x50, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x18, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x7e, 0x0a, 0x22, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x70, 0x61, 0x67, 0x65,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2f, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x00, 0x52, 0x1f, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x69, 0x72,
	0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0e, 0x70,
	0x65, 0x65, 0x72, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x70, 0x65, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x62, 0x0a, 0x18, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x70, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52,
	0x16, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x48, 0x61, 0x73, 0x68, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x3c, 0x0a, 0x0d, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x22, 0x2e, 0x0a, 0x12, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0xc0, 0x01, 0x0a, 0x12, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0e, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00,
	0x52, 0x0d, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x56, 0x0a, 0x14, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x12, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x1a, 0x5a, 0x18, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_qry_responses_proto_rawDescOnce sync.Once
	file_qry_responses_proto_rawDescData = file_qry_responses_proto_rawDesc
)

func file_qry_responses_proto_rawDescGZIP() []byte {
	file_qry_responses_proto_rawDescOnce.Do(func() {
		file_qry_responses_proto_rawDescData = protoimpl.X.CompressGZIP(file_qry_responses_proto_rawDescData)
	})
	return file_qry_responses_proto_rawDescData
}

var file_qry_responses_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_qry_responses_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_qry_responses_proto_goTypes = []interface{}{
	(ErrorResponse_Reason)(0),                         // 0: iroha.protocol.ErrorResponse.Reason
	(*Asset)(nil),                                     // 1: iroha.protocol.Asset
	(*Domain)(nil),                                    // 2: iroha.protocol.Domain
	(*Account)(nil),                                   // 3: iroha.protocol.Account
	(*AccountAsset)(nil),                              // 4: iroha.protocol.AccountAsset
	(*AccountAssetResponse)(nil),                      // 5: iroha.protocol.AccountAssetResponse
	(*AccountDetailResponse)(nil),                     // 6: iroha.protocol.AccountDetailResponse
	(*AccountResponse)(nil),                           // 7: iroha.protocol.AccountResponse
	(*AssetResponse)(nil),                             // 8: iroha.protocol.AssetResponse
	(*RolesResponse)(nil),                             // 9: iroha.protocol.RolesResponse
	(*RolePermissionsResponse)(nil),                   // 10: iroha.protocol.RolePermissionsResponse
	(*ErrorResponse)(nil),                             // 11: iroha.protocol.ErrorResponse
	(*SignatoriesResponse)(nil),                       // 12: iroha.protocol.SignatoriesResponse
	(*TransactionsResponse)(nil),                      // 13: iroha.protocol.TransactionsResponse
	(*TransactionsPageResponse)(nil),                  // 14: iroha.protocol.TransactionsPageResponse
	(*PendingTransactionsPageResponse)(nil),           // 15: iroha.protocol.PendingTransactionsPageResponse
	(*PeersResponse)(nil),                             // 16: iroha.protocol.PeersResponse
	(*EngineReceiptsResponse)(nil),                    // 17: iroha.protocol.EngineReceiptsResponse
	(*QueryResponse)(nil),                             // 18: iroha.protocol.QueryResponse
	(*BlockResponse)(nil),                             // 19: iroha.protocol.BlockResponse
	(*BlockErrorResponse)(nil),                        // 20: iroha.protocol.BlockErrorResponse
	(*BlockQueryResponse)(nil),                        // 21: iroha.protocol.BlockQueryResponse
	(*PendingTransactionsPageResponse_BatchInfo)(nil), // 22: iroha.protocol.PendingTransactionsPageResponse.BatchInfo
	(*AccountDetailRecordId)(nil),                     // 23: iroha.protocol.AccountDetailRecordId
	(RolePermission)(0),                               // 24: iroha.protocol.RolePermission
	(*Transaction)(nil),                               // 25: iroha.protocol.Transaction
	(*Peer)(nil),                                      // 26: iroha.protocol.Peer
	(*EngineReceipt)(nil),                             // 27: iroha.protocol.EngineReceipt
	(*Block)(nil),                                     // 28: iroha.protocol.Block
}
var file_qry_responses_proto_depIdxs = []int32{
	4,  // 0: iroha.protocol.AccountAssetResponse.account_assets:type_name -> iroha.protocol.AccountAsset
	23, // 1: iroha.protocol.AccountDetailResponse.next_record_id:type_name -> iroha.protocol.AccountDetailRecordId
	3,  // 2: iroha.protocol.AccountResponse.account:type_name -> iroha.protocol.Account
	1,  // 3: iroha.protocol.AssetResponse.asset:type_name -> iroha.protocol.Asset
	24, // 4: iroha.protocol.RolePermissionsResponse.permissions:type_name -> iroha.protocol.RolePermission
	0,  // 5: iroha.protocol.ErrorResponse.reason:type_name -> iroha.protocol.ErrorResponse.Reason
	25, // 6: iroha.protocol.TransactionsResponse.transactions:type_name -> iroha.protocol.Transaction
	25, // 7: iroha.protocol.TransactionsPageResponse.transactions:type_name -> iroha.protocol.Transaction
	25, // 8: iroha.protocol.PendingTransactionsPageResponse.transactions:type_name -> iroha.protocol.Transaction
	22, // 9: iroha.protocol.PendingTransactionsPageResponse.next_batch_info:type_name -> iroha.protocol.PendingTransactionsPageResponse.BatchInfo
	26, // 10: iroha.protocol.PeersResponse.peers:type_name -> iroha.protocol.Peer
	27, // 11: iroha.protocol.EngineReceiptsResponse.engine_receipts:type_name -> iroha.protocol.EngineReceipt
	5,  // 12: iroha.protocol.QueryResponse.account_assets_response:type_name -> iroha.protocol.AccountAssetResponse
	6,  // 13: iroha.protocol.QueryResponse.account_detail_response:type_name -> iroha.protocol.AccountDetailResponse
	7,  // 14: iroha.protocol.QueryResponse.account_response:type_name -> iroha.protocol.AccountResponse
	11, // 15: iroha.protocol.QueryResponse.error_response:type_name -> iroha.protocol.ErrorResponse
	12, // 16: iroha.protocol.QueryResponse.signatories_response:type_name -> iroha.protocol.SignatoriesResponse
	13, // 17: iroha.protocol.QueryResponse.transactions_response:type_name -> iroha.protocol.TransactionsResponse
	8,  // 18: iroha.protocol.QueryResponse.asset_response:type_name -> iroha.protocol.AssetResponse
	9,  // 19: iroha.protocol.QueryResponse.roles_response:type_name -> iroha.protocol.RolesResponse
	10, // 20: iroha.protocol.QueryResponse.role_permissions_response:type_name -> iroha.protocol.RolePermissionsResponse
	14, // 21: iroha.protocol.QueryResponse.transactions_page_response:type_name -> iroha.protocol.TransactionsPageResponse
	15, // 22: iroha.protocol.QueryResponse.pending_transactions_page_response:type_name -> iroha.protocol.PendingTransactionsPageResponse
	19, // 23: iroha.protocol.QueryResponse.block_response:type_name -> iroha.protocol.BlockResponse
	16, // 24: iroha.protocol.QueryResponse.peers_response:type_name -> iroha.protocol.PeersResponse
	17, // 25: iroha.protocol.QueryResponse.engine_receipts_response:type_name -> iroha.protocol.EngineReceiptsResponse
	28, // 26: iroha.protocol.BlockResponse.block:type_name -> iroha.protocol.Block
	19, // 27: iroha.protocol.BlockQueryResponse.block_response:type_name -> iroha.protocol.BlockResponse
	20, // 28: iroha.protocol.BlockQueryResponse.block_error_response:type_name -> iroha.protocol.BlockErrorResponse
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_qry_responses_proto_init() }
func file_qry_responses_proto_init() {
	if File_qry_responses_proto != nil {
		return
	}
	file_block_proto_init()
	file_transaction_proto_init()
	file_primitive_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_qry_responses_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Asset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qry_responses_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Domain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qry_responses_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Account); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qry_responses_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountAsset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qry_responses_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountAssetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qry_responses_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qry_responses_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qry_responses_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qry_responses_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RolesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qry_responses_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RolePermissionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qry_responses_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qry_responses_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignatoriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qry_responses_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qry_responses_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionsPageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qry_responses_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PendingTransactionsPageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qry_responses_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qry_responses_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EngineReceiptsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qry_responses_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qry_responses_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qry_responses_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qry_responses_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockQueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qry_responses_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PendingTransactionsPageResponse_BatchInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_qry_responses_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*AccountAssetResponse_NextAssetId)(nil),
	}
	file_qry_responses_proto_msgTypes[13].OneofWrappers = []interface{}{
		(*TransactionsPageResponse_NextTxHash)(nil),
	}
	file_qry_responses_proto_msgTypes[17].OneofWrappers = []interface{}{
		(*QueryResponse_AccountAssetsResponse)(nil),
		(*QueryResponse_AccountDetailResponse)(nil),
		(*QueryResponse_AccountResponse)(nil),
		(*QueryResponse_ErrorResponse)(nil),
		(*QueryResponse_SignatoriesResponse)(nil),
		(*QueryResponse_TransactionsResponse)(nil),
		(*QueryResponse_AssetResponse)(nil),
		(*QueryResponse_RolesResponse)(nil),
		(*QueryResponse_RolePermissionsResponse)(nil),
		(*QueryResponse_TransactionsPageResponse)(nil),
		(*QueryResponse_PendingTransactionsPageResponse)(nil),
		(*QueryResponse_BlockResponse)(nil),
		(*QueryResponse_PeersResponse)(nil),
		(*QueryResponse_EngineReceiptsResponse)(nil),
	}
	file_qry_responses_proto_msgTypes[20].OneofWrappers = []interface{}{
		(*BlockQueryResponse_BlockResponse)(nil),
		(*BlockQueryResponse_BlockErrorResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_qry_responses_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qry_responses_proto_goTypes,
		DependencyIndexes: file_qry_responses_proto_depIdxs,
		EnumInfos:         file_qry_responses_proto_enumTypes,
		MessageInfos:      file_qry_responses_proto_msgTypes,
	}.Build()
	File_qry_responses_proto = out.File
	file_qry_responses_proto_rawDesc = nil
	file_qry_responses_proto_goTypes = nil
	file_qry_responses_proto_depIdxs = nil
}
