//*
// Copyright Soramitsu Co., Ltd. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.11.2
// source: queries.proto

package protocol

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Field int32

const (
	Field_kCreatedTime Field = 0
	Field_kPosition    Field = 1
)

// Enum value maps for Field.
var (
	Field_name = map[int32]string{
		0: "kCreatedTime",
		1: "kPosition",
	}
	Field_value = map[string]int32{
		"kCreatedTime": 0,
		"kPosition":    1,
	}
)

func (x Field) Enum() *Field {
	p := new(Field)
	*p = x
	return p
}

func (x Field) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Field) Descriptor() protoreflect.EnumDescriptor {
	return file_queries_proto_enumTypes[0].Descriptor()
}

func (Field) Type() protoreflect.EnumType {
	return &file_queries_proto_enumTypes[0]
}

func (x Field) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Field.Descriptor instead.
func (Field) EnumDescriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{0}
}

type Direction int32

const (
	Direction_kAscending  Direction = 0
	Direction_kDescending Direction = 1
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "kAscending",
		1: "kDescending",
	}
	Direction_value = map[string]int32{
		"kAscending":  0,
		"kDescending": 1,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_queries_proto_enumTypes[1].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_queries_proto_enumTypes[1]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{1}
}

type Ordering struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sequence []*Ordering_FieldOrdering `protobuf:"bytes,1,rep,name=sequence,proto3" json:"sequence,omitempty"`
}

func (x *Ordering) Reset() {
	*x = Ordering{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ordering) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ordering) ProtoMessage() {}

func (x *Ordering) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ordering.ProtoReflect.Descriptor instead.
func (*Ordering) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{0}
}

func (x *Ordering) GetSequence() []*Ordering_FieldOrdering {
	if x != nil {
		return x.Sequence
	}
	return nil
}

type TxPaginationMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageSize uint32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Types that are assignable to OptFirstTxHash:
	//	*TxPaginationMeta_FirstTxHash
	OptFirstTxHash isTxPaginationMeta_OptFirstTxHash `protobuf_oneof:"opt_first_tx_hash"`
	Ordering       *Ordering                         `protobuf:"bytes,3,opt,name=ordering,proto3" json:"ordering,omitempty"`
	// Types that are assignable to OptFirstTxTime:
	//	*TxPaginationMeta_FirstTxTime
	OptFirstTxTime isTxPaginationMeta_OptFirstTxTime `protobuf_oneof:"opt_first_tx_time"`
	// Types that are assignable to OptLastTxTime:
	//	*TxPaginationMeta_LastTxTime
	OptLastTxTime isTxPaginationMeta_OptLastTxTime `protobuf_oneof:"opt_last_tx_time"`
	// Types that are assignable to OptFirstTxHeight:
	//	*TxPaginationMeta_FirstTxHeight
	OptFirstTxHeight isTxPaginationMeta_OptFirstTxHeight `protobuf_oneof:"opt_first_tx_height"`
	// Types that are assignable to OptLastTxHeight:
	//	*TxPaginationMeta_LastTxHeight
	OptLastTxHeight isTxPaginationMeta_OptLastTxHeight `protobuf_oneof:"opt_last_tx_height"`
}

func (x *TxPaginationMeta) Reset() {
	*x = TxPaginationMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxPaginationMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxPaginationMeta) ProtoMessage() {}

func (x *TxPaginationMeta) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxPaginationMeta.ProtoReflect.Descriptor instead.
func (*TxPaginationMeta) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{1}
}

func (x *TxPaginationMeta) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (m *TxPaginationMeta) GetOptFirstTxHash() isTxPaginationMeta_OptFirstTxHash {
	if m != nil {
		return m.OptFirstTxHash
	}
	return nil
}

func (x *TxPaginationMeta) GetFirstTxHash() string {
	if x, ok := x.GetOptFirstTxHash().(*TxPaginationMeta_FirstTxHash); ok {
		return x.FirstTxHash
	}
	return ""
}

func (x *TxPaginationMeta) GetOrdering() *Ordering {
	if x != nil {
		return x.Ordering
	}
	return nil
}

func (m *TxPaginationMeta) GetOptFirstTxTime() isTxPaginationMeta_OptFirstTxTime {
	if m != nil {
		return m.OptFirstTxTime
	}
	return nil
}

func (x *TxPaginationMeta) GetFirstTxTime() *timestamp.Timestamp {
	if x, ok := x.GetOptFirstTxTime().(*TxPaginationMeta_FirstTxTime); ok {
		return x.FirstTxTime
	}
	return nil
}

func (m *TxPaginationMeta) GetOptLastTxTime() isTxPaginationMeta_OptLastTxTime {
	if m != nil {
		return m.OptLastTxTime
	}
	return nil
}

func (x *TxPaginationMeta) GetLastTxTime() *timestamp.Timestamp {
	if x, ok := x.GetOptLastTxTime().(*TxPaginationMeta_LastTxTime); ok {
		return x.LastTxTime
	}
	return nil
}

func (m *TxPaginationMeta) GetOptFirstTxHeight() isTxPaginationMeta_OptFirstTxHeight {
	if m != nil {
		return m.OptFirstTxHeight
	}
	return nil
}

func (x *TxPaginationMeta) GetFirstTxHeight() uint64 {
	if x, ok := x.GetOptFirstTxHeight().(*TxPaginationMeta_FirstTxHeight); ok {
		return x.FirstTxHeight
	}
	return 0
}

func (m *TxPaginationMeta) GetOptLastTxHeight() isTxPaginationMeta_OptLastTxHeight {
	if m != nil {
		return m.OptLastTxHeight
	}
	return nil
}

func (x *TxPaginationMeta) GetLastTxHeight() uint64 {
	if x, ok := x.GetOptLastTxHeight().(*TxPaginationMeta_LastTxHeight); ok {
		return x.LastTxHeight
	}
	return 0
}

type isTxPaginationMeta_OptFirstTxHash interface {
	isTxPaginationMeta_OptFirstTxHash()
}

type TxPaginationMeta_FirstTxHash struct {
	FirstTxHash string `protobuf:"bytes,2,opt,name=first_tx_hash,json=firstTxHash,proto3,oneof"`
}

func (*TxPaginationMeta_FirstTxHash) isTxPaginationMeta_OptFirstTxHash() {}

type isTxPaginationMeta_OptFirstTxTime interface {
	isTxPaginationMeta_OptFirstTxTime()
}

type TxPaginationMeta_FirstTxTime struct {
	FirstTxTime *timestamp.Timestamp `protobuf:"bytes,4,opt,name=first_tx_time,json=firstTxTime,proto3,oneof"`
}

func (*TxPaginationMeta_FirstTxTime) isTxPaginationMeta_OptFirstTxTime() {}

type isTxPaginationMeta_OptLastTxTime interface {
	isTxPaginationMeta_OptLastTxTime()
}

type TxPaginationMeta_LastTxTime struct {
	LastTxTime *timestamp.Timestamp `protobuf:"bytes,5,opt,name=last_tx_time,json=lastTxTime,proto3,oneof"`
}

func (*TxPaginationMeta_LastTxTime) isTxPaginationMeta_OptLastTxTime() {}

type isTxPaginationMeta_OptFirstTxHeight interface {
	isTxPaginationMeta_OptFirstTxHeight()
}

type TxPaginationMeta_FirstTxHeight struct {
	FirstTxHeight uint64 `protobuf:"varint,6,opt,name=first_tx_height,json=firstTxHeight,proto3,oneof"`
}

func (*TxPaginationMeta_FirstTxHeight) isTxPaginationMeta_OptFirstTxHeight() {}

type isTxPaginationMeta_OptLastTxHeight interface {
	isTxPaginationMeta_OptLastTxHeight()
}

type TxPaginationMeta_LastTxHeight struct {
	LastTxHeight uint64 `protobuf:"varint,7,opt,name=last_tx_height,json=lastTxHeight,proto3,oneof"`
}

func (*TxPaginationMeta_LastTxHeight) isTxPaginationMeta_OptLastTxHeight() {}

type AssetPaginationMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageSize uint32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Types that are assignable to OptFirstAssetId:
	//	*AssetPaginationMeta_FirstAssetId
	OptFirstAssetId isAssetPaginationMeta_OptFirstAssetId `protobuf_oneof:"opt_first_asset_id"`
}

func (x *AssetPaginationMeta) Reset() {
	*x = AssetPaginationMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssetPaginationMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetPaginationMeta) ProtoMessage() {}

func (x *AssetPaginationMeta) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetPaginationMeta.ProtoReflect.Descriptor instead.
func (*AssetPaginationMeta) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{2}
}

func (x *AssetPaginationMeta) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (m *AssetPaginationMeta) GetOptFirstAssetId() isAssetPaginationMeta_OptFirstAssetId {
	if m != nil {
		return m.OptFirstAssetId
	}
	return nil
}

func (x *AssetPaginationMeta) GetFirstAssetId() string {
	if x, ok := x.GetOptFirstAssetId().(*AssetPaginationMeta_FirstAssetId); ok {
		return x.FirstAssetId
	}
	return ""
}

type isAssetPaginationMeta_OptFirstAssetId interface {
	isAssetPaginationMeta_OptFirstAssetId()
}

type AssetPaginationMeta_FirstAssetId struct {
	FirstAssetId string `protobuf:"bytes,2,opt,name=first_asset_id,json=firstAssetId,proto3,oneof"`
}

func (*AssetPaginationMeta_FirstAssetId) isAssetPaginationMeta_OptFirstAssetId() {}

type GetAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
}

func (x *GetAccount) Reset() {
	*x = GetAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccount) ProtoMessage() {}

func (x *GetAccount) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccount.ProtoReflect.Descriptor instead.
func (*GetAccount) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccount) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *GetBlock) Reset() {
	*x = GetBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlock) ProtoMessage() {}

func (x *GetBlock) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlock.ProtoReflect.Descriptor instead.
func (*GetBlock) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{4}
}

func (x *GetBlock) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GetSignatories struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
}

func (x *GetSignatories) Reset() {
	*x = GetSignatories{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSignatories) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignatories) ProtoMessage() {}

func (x *GetSignatories) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignatories.ProtoReflect.Descriptor instead.
func (*GetSignatories) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{5}
}

func (x *GetSignatories) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetAccountTransactions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId      string            `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	PaginationMeta *TxPaginationMeta `protobuf:"bytes,2,opt,name=pagination_meta,json=paginationMeta,proto3" json:"pagination_meta,omitempty"`
}

func (x *GetAccountTransactions) Reset() {
	*x = GetAccountTransactions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountTransactions) ProtoMessage() {}

func (x *GetAccountTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountTransactions.ProtoReflect.Descriptor instead.
func (*GetAccountTransactions) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{6}
}

func (x *GetAccountTransactions) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetAccountTransactions) GetPaginationMeta() *TxPaginationMeta {
	if x != nil {
		return x.PaginationMeta
	}
	return nil
}

type GetAccountAssetTransactions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId      string            `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AssetId        string            `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	PaginationMeta *TxPaginationMeta `protobuf:"bytes,3,opt,name=pagination_meta,json=paginationMeta,proto3" json:"pagination_meta,omitempty"`
}

func (x *GetAccountAssetTransactions) Reset() {
	*x = GetAccountAssetTransactions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountAssetTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountAssetTransactions) ProtoMessage() {}

func (x *GetAccountAssetTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountAssetTransactions.ProtoReflect.Descriptor instead.
func (*GetAccountAssetTransactions) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{7}
}

func (x *GetAccountAssetTransactions) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetAccountAssetTransactions) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *GetAccountAssetTransactions) GetPaginationMeta() *TxPaginationMeta {
	if x != nil {
		return x.PaginationMeta
	}
	return nil
}

type GetTransactions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxHashes []string `protobuf:"bytes,1,rep,name=tx_hashes,json=txHashes,proto3" json:"tx_hashes,omitempty"`
}

func (x *GetTransactions) Reset() {
	*x = GetTransactions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactions) ProtoMessage() {}

func (x *GetTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactions.ProtoReflect.Descriptor instead.
func (*GetTransactions) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{8}
}

func (x *GetTransactions) GetTxHashes() []string {
	if x != nil {
		return x.TxHashes
	}
	return nil
}

type GetAccountAssets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId      string               `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	PaginationMeta *AssetPaginationMeta `protobuf:"bytes,2,opt,name=pagination_meta,json=paginationMeta,proto3" json:"pagination_meta,omitempty"`
}

func (x *GetAccountAssets) Reset() {
	*x = GetAccountAssets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountAssets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountAssets) ProtoMessage() {}

func (x *GetAccountAssets) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountAssets.ProtoReflect.Descriptor instead.
func (*GetAccountAssets) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{9}
}

func (x *GetAccountAssets) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetAccountAssets) GetPaginationMeta() *AssetPaginationMeta {
	if x != nil {
		return x.PaginationMeta
	}
	return nil
}

type AccountDetailPaginationMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageSize      uint32                 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	FirstRecordId *AccountDetailRecordId `protobuf:"bytes,2,opt,name=first_record_id,json=firstRecordId,proto3" json:"first_record_id,omitempty"`
}

func (x *AccountDetailPaginationMeta) Reset() {
	*x = AccountDetailPaginationMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountDetailPaginationMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountDetailPaginationMeta) ProtoMessage() {}

func (x *AccountDetailPaginationMeta) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountDetailPaginationMeta.ProtoReflect.Descriptor instead.
func (*AccountDetailPaginationMeta) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{10}
}

func (x *AccountDetailPaginationMeta) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AccountDetailPaginationMeta) GetFirstRecordId() *AccountDetailRecordId {
	if x != nil {
		return x.FirstRecordId
	}
	return nil
}

type GetAccountDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to OptAccountId:
	//	*GetAccountDetail_AccountId
	OptAccountId isGetAccountDetail_OptAccountId `protobuf_oneof:"opt_account_id"`
	// Types that are assignable to OptKey:
	//	*GetAccountDetail_Key
	OptKey isGetAccountDetail_OptKey `protobuf_oneof:"opt_key"`
	// Types that are assignable to OptWriter:
	//	*GetAccountDetail_Writer
	OptWriter      isGetAccountDetail_OptWriter `protobuf_oneof:"opt_writer"`
	PaginationMeta *AccountDetailPaginationMeta `protobuf:"bytes,4,opt,name=pagination_meta,json=paginationMeta,proto3" json:"pagination_meta,omitempty"`
}

func (x *GetAccountDetail) Reset() {
	*x = GetAccountDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountDetail) ProtoMessage() {}

func (x *GetAccountDetail) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountDetail.ProtoReflect.Descriptor instead.
func (*GetAccountDetail) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{11}
}

func (m *GetAccountDetail) GetOptAccountId() isGetAccountDetail_OptAccountId {
	if m != nil {
		return m.OptAccountId
	}
	return nil
}

func (x *GetAccountDetail) GetAccountId() string {
	if x, ok := x.GetOptAccountId().(*GetAccountDetail_AccountId); ok {
		return x.AccountId
	}
	return ""
}

func (m *GetAccountDetail) GetOptKey() isGetAccountDetail_OptKey {
	if m != nil {
		return m.OptKey
	}
	return nil
}

func (x *GetAccountDetail) GetKey() string {
	if x, ok := x.GetOptKey().(*GetAccountDetail_Key); ok {
		return x.Key
	}
	return ""
}

func (m *GetAccountDetail) GetOptWriter() isGetAccountDetail_OptWriter {
	if m != nil {
		return m.OptWriter
	}
	return nil
}

func (x *GetAccountDetail) GetWriter() string {
	if x, ok := x.GetOptWriter().(*GetAccountDetail_Writer); ok {
		return x.Writer
	}
	return ""
}

func (x *GetAccountDetail) GetPaginationMeta() *AccountDetailPaginationMeta {
	if x != nil {
		return x.PaginationMeta
	}
	return nil
}

type isGetAccountDetail_OptAccountId interface {
	isGetAccountDetail_OptAccountId()
}

type GetAccountDetail_AccountId struct {
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3,oneof"`
}

func (*GetAccountDetail_AccountId) isGetAccountDetail_OptAccountId() {}

type isGetAccountDetail_OptKey interface {
	isGetAccountDetail_OptKey()
}

type GetAccountDetail_Key struct {
	Key string `protobuf:"bytes,2,opt,name=key,proto3,oneof"`
}

func (*GetAccountDetail_Key) isGetAccountDetail_OptKey() {}

type isGetAccountDetail_OptWriter interface {
	isGetAccountDetail_OptWriter()
}

type GetAccountDetail_Writer struct {
	Writer string `protobuf:"bytes,3,opt,name=writer,proto3,oneof"`
}

func (*GetAccountDetail_Writer) isGetAccountDetail_OptWriter() {}

type GetAssetInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetId string `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
}

func (x *GetAssetInfo) Reset() {
	*x = GetAssetInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAssetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetInfo) ProtoMessage() {}

func (x *GetAssetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetInfo.ProtoReflect.Descriptor instead.
func (*GetAssetInfo) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{12}
}

func (x *GetAssetInfo) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

type GetRoles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRoles) Reset() {
	*x = GetRoles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoles) ProtoMessage() {}

func (x *GetRoles) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoles.ProtoReflect.Descriptor instead.
func (*GetRoles) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{13}
}

type GetRolePermissions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId string `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
}

func (x *GetRolePermissions) Reset() {
	*x = GetRolePermissions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRolePermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePermissions) ProtoMessage() {}

func (x *GetRolePermissions) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePermissions.ProtoReflect.Descriptor instead.
func (*GetRolePermissions) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{14}
}

func (x *GetRolePermissions) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type GetPendingTransactions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaginationMeta *TxPaginationMeta `protobuf:"bytes,1,opt,name=pagination_meta,json=paginationMeta,proto3" json:"pagination_meta,omitempty"`
}

func (x *GetPendingTransactions) Reset() {
	*x = GetPendingTransactions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPendingTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingTransactions) ProtoMessage() {}

func (x *GetPendingTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingTransactions.ProtoReflect.Descriptor instead.
func (*GetPendingTransactions) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{15}
}

func (x *GetPendingTransactions) GetPaginationMeta() *TxPaginationMeta {
	if x != nil {
		return x.PaginationMeta
	}
	return nil
}

type GetPeers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPeers) Reset() {
	*x = GetPeers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPeers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeers) ProtoMessage() {}

func (x *GetPeers) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeers.ProtoReflect.Descriptor instead.
func (*GetPeers) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{16}
}

type QueryPayloadMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatedTime      uint64 `protobuf:"varint,1,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	CreatorAccountId string `protobuf:"bytes,2,opt,name=creator_account_id,json=creatorAccountId,proto3" json:"creator_account_id,omitempty"`
	// used to prevent replay attacks.
	QueryCounter uint64 `protobuf:"varint,3,opt,name=query_counter,json=queryCounter,proto3" json:"query_counter,omitempty"`
}

func (x *QueryPayloadMeta) Reset() {
	*x = QueryPayloadMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryPayloadMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPayloadMeta) ProtoMessage() {}

func (x *QueryPayloadMeta) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPayloadMeta.ProtoReflect.Descriptor instead.
func (*QueryPayloadMeta) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{17}
}

func (x *QueryPayloadMeta) GetCreatedTime() uint64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

func (x *QueryPayloadMeta) GetCreatorAccountId() string {
	if x != nil {
		return x.CreatorAccountId
	}
	return ""
}

func (x *QueryPayloadMeta) GetQueryCounter() uint64 {
	if x != nil {
		return x.QueryCounter
	}
	return 0
}

type GetEngineReceipts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxHash string `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
}

func (x *GetEngineReceipts) Reset() {
	*x = GetEngineReceipts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEngineReceipts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEngineReceipts) ProtoMessage() {}

func (x *GetEngineReceipts) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEngineReceipts.ProtoReflect.Descriptor instead.
func (*GetEngineReceipts) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{18}
}

func (x *GetEngineReceipts) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type Query struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload   *Query_Payload `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature *Signature     `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *Query) Reset() {
	*x = Query{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{19}
}

func (x *Query) GetPayload() *Query_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Query) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

type BlocksQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta      *QueryPayloadMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Signature *Signature        `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *BlocksQuery) Reset() {
	*x = BlocksQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlocksQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlocksQuery) ProtoMessage() {}

func (x *BlocksQuery) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlocksQuery.ProtoReflect.Descriptor instead.
func (*BlocksQuery) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{20}
}

func (x *BlocksQuery) GetMeta() *QueryPayloadMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *BlocksQuery) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Ordering_FieldOrdering struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field     Field     `protobuf:"varint,1,opt,name=field,proto3,enum=iroha.protocol.Field" json:"field,omitempty"`
	Direction Direction `protobuf:"varint,2,opt,name=direction,proto3,enum=iroha.protocol.Direction" json:"direction,omitempty"`
}

func (x *Ordering_FieldOrdering) Reset() {
	*x = Ordering_FieldOrdering{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ordering_FieldOrdering) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ordering_FieldOrdering) ProtoMessage() {}

func (x *Ordering_FieldOrdering) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ordering_FieldOrdering.ProtoReflect.Descriptor instead.
func (*Ordering_FieldOrdering) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Ordering_FieldOrdering) GetField() Field {
	if x != nil {
		return x.Field
	}
	return Field_kCreatedTime
}

func (x *Ordering_FieldOrdering) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_kAscending
}

type Query_Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta *QueryPayloadMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Types that are assignable to Query:
	//	*Query_Payload_GetAccount
	//	*Query_Payload_GetSignatories
	//	*Query_Payload_GetAccountTransactions
	//	*Query_Payload_GetAccountAssetTransactions
	//	*Query_Payload_GetTransactions
	//	*Query_Payload_GetAccountAssets
	//	*Query_Payload_GetAccountDetail
	//	*Query_Payload_GetRoles
	//	*Query_Payload_GetRolePermissions
	//	*Query_Payload_GetAssetInfo
	//	*Query_Payload_GetPendingTransactions
	//	*Query_Payload_GetBlock
	//	*Query_Payload_GetPeers
	//	*Query_Payload_GetEngineReceipts
	Query isQuery_Payload_Query `protobuf_oneof:"query"`
}

func (x *Query_Payload) Reset() {
	*x = Query_Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_queries_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Payload) ProtoMessage() {}

func (x *Query_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_queries_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Payload.ProtoReflect.Descriptor instead.
func (*Query_Payload) Descriptor() ([]byte, []int) {
	return file_queries_proto_rawDescGZIP(), []int{19, 0}
}

func (x *Query_Payload) GetMeta() *QueryPayloadMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (m *Query_Payload) GetQuery() isQuery_Payload_Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (x *Query_Payload) GetGetAccount() *GetAccount {
	if x, ok := x.GetQuery().(*Query_Payload_GetAccount); ok {
		return x.GetAccount
	}
	return nil
}

func (x *Query_Payload) GetGetSignatories() *GetSignatories {
	if x, ok := x.GetQuery().(*Query_Payload_GetSignatories); ok {
		return x.GetSignatories
	}
	return nil
}

func (x *Query_Payload) GetGetAccountTransactions() *GetAccountTransactions {
	if x, ok := x.GetQuery().(*Query_Payload_GetAccountTransactions); ok {
		return x.GetAccountTransactions
	}
	return nil
}

func (x *Query_Payload) GetGetAccountAssetTransactions() *GetAccountAssetTransactions {
	if x, ok := x.GetQuery().(*Query_Payload_GetAccountAssetTransactions); ok {
		return x.GetAccountAssetTransactions
	}
	return nil
}

func (x *Query_Payload) GetGetTransactions() *GetTransactions {
	if x, ok := x.GetQuery().(*Query_Payload_GetTransactions); ok {
		return x.GetTransactions
	}
	return nil
}

func (x *Query_Payload) GetGetAccountAssets() *GetAccountAssets {
	if x, ok := x.GetQuery().(*Query_Payload_GetAccountAssets); ok {
		return x.GetAccountAssets
	}
	return nil
}

func (x *Query_Payload) GetGetAccountDetail() *GetAccountDetail {
	if x, ok := x.GetQuery().(*Query_Payload_GetAccountDetail); ok {
		return x.GetAccountDetail
	}
	return nil
}

func (x *Query_Payload) GetGetRoles() *GetRoles {
	if x, ok := x.GetQuery().(*Query_Payload_GetRoles); ok {
		return x.GetRoles
	}
	return nil
}

func (x *Query_Payload) GetGetRolePermissions() *GetRolePermissions {
	if x, ok := x.GetQuery().(*Query_Payload_GetRolePermissions); ok {
		return x.GetRolePermissions
	}
	return nil
}

func (x *Query_Payload) GetGetAssetInfo() *GetAssetInfo {
	if x, ok := x.GetQuery().(*Query_Payload_GetAssetInfo); ok {
		return x.GetAssetInfo
	}
	return nil
}

func (x *Query_Payload) GetGetPendingTransactions() *GetPendingTransactions {
	if x, ok := x.GetQuery().(*Query_Payload_GetPendingTransactions); ok {
		return x.GetPendingTransactions
	}
	return nil
}

func (x *Query_Payload) GetGetBlock() *GetBlock {
	if x, ok := x.GetQuery().(*Query_Payload_GetBlock); ok {
		return x.GetBlock
	}
	return nil
}

func (x *Query_Payload) GetGetPeers() *GetPeers {
	if x, ok := x.GetQuery().(*Query_Payload_GetPeers); ok {
		return x.GetPeers
	}
	return nil
}

func (x *Query_Payload) GetGetEngineReceipts() *GetEngineReceipts {
	if x, ok := x.GetQuery().(*Query_Payload_GetEngineReceipts); ok {
		return x.GetEngineReceipts
	}
	return nil
}

type isQuery_Payload_Query interface {
	isQuery_Payload_Query()
}

type Query_Payload_GetAccount struct {
	GetAccount *GetAccount `protobuf:"bytes,3,opt,name=get_account,json=getAccount,proto3,oneof"`
}

type Query_Payload_GetSignatories struct {
	GetSignatories *GetSignatories `protobuf:"bytes,4,opt,name=get_signatories,json=getSignatories,proto3,oneof"`
}

type Query_Payload_GetAccountTransactions struct {
	GetAccountTransactions *GetAccountTransactions `protobuf:"bytes,5,opt,name=get_account_transactions,json=getAccountTransactions,proto3,oneof"`
}

type Query_Payload_GetAccountAssetTransactions struct {
	GetAccountAssetTransactions *GetAccountAssetTransactions `protobuf:"bytes,6,opt,name=get_account_asset_transactions,json=getAccountAssetTransactions,proto3,oneof"`
}

type Query_Payload_GetTransactions struct {
	GetTransactions *GetTransactions `protobuf:"bytes,7,opt,name=get_transactions,json=getTransactions,proto3,oneof"`
}

type Query_Payload_GetAccountAssets struct {
	GetAccountAssets *GetAccountAssets `protobuf:"bytes,8,opt,name=get_account_assets,json=getAccountAssets,proto3,oneof"`
}

type Query_Payload_GetAccountDetail struct {
	GetAccountDetail *GetAccountDetail `protobuf:"bytes,9,opt,name=get_account_detail,json=getAccountDetail,proto3,oneof"`
}

type Query_Payload_GetRoles struct {
	GetRoles *GetRoles `protobuf:"bytes,10,opt,name=get_roles,json=getRoles,proto3,oneof"`
}

type Query_Payload_GetRolePermissions struct {
	GetRolePermissions *GetRolePermissions `protobuf:"bytes,11,opt,name=get_role_permissions,json=getRolePermissions,proto3,oneof"`
}

type Query_Payload_GetAssetInfo struct {
	GetAssetInfo *GetAssetInfo `protobuf:"bytes,12,opt,name=get_asset_info,json=getAssetInfo,proto3,oneof"`
}

type Query_Payload_GetPendingTransactions struct {
	GetPendingTransactions *GetPendingTransactions `protobuf:"bytes,13,opt,name=get_pending_transactions,json=getPendingTransactions,proto3,oneof"`
}

type Query_Payload_GetBlock struct {
	GetBlock *GetBlock `protobuf:"bytes,14,opt,name=get_block,json=getBlock,proto3,oneof"`
}

type Query_Payload_GetPeers struct {
	GetPeers *GetPeers `protobuf:"bytes,15,opt,name=get_peers,json=getPeers,proto3,oneof"`
}

type Query_Payload_GetEngineReceipts struct {
	GetEngineReceipts *GetEngineReceipts `protobuf:"bytes,16,opt,name=get_engine_receipts,json=getEngineReceipts,proto3,oneof"`
}

func (*Query_Payload_GetAccount) isQuery_Payload_Query() {}

func (*Query_Payload_GetSignatories) isQuery_Payload_Query() {}

func (*Query_Payload_GetAccountTransactions) isQuery_Payload_Query() {}

func (*Query_Payload_GetAccountAssetTransactions) isQuery_Payload_Query() {}

func (*Query_Payload_GetTransactions) isQuery_Payload_Query() {}

func (*Query_Payload_GetAccountAssets) isQuery_Payload_Query() {}

func (*Query_Payload_GetAccountDetail) isQuery_Payload_Query() {}

func (*Query_Payload_GetRoles) isQuery_Payload_Query() {}

func (*Query_Payload_GetRolePermissions) isQuery_Payload_Query() {}

func (*Query_Payload_GetAssetInfo) isQuery_Payload_Query() {}

func (*Query_Payload_GetPendingTransactions) isQuery_Payload_Query() {}

func (*Query_Payload_GetBlock) isQuery_Payload_Query() {}

func (*Query_Payload_GetPeers) isQuery_Payload_Query() {}

func (*Query_Payload_GetEngineReceipts) isQuery_Payload_Query() {}

var File_queries_proto protoreflect.FileDescriptor

var file_queries_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a,
	0x0f, 0x70, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xc5, 0x01, 0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x42,
	0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x26, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x1a, 0x75, 0x0a, 0x0d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x69, 0x6e, 0x67, 0x12, 0x2b, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x15, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x12, 0x37, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xca, 0x03, 0x0a, 0x10, 0x54, 0x78,
	0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x66,
	0x69, 0x72, 0x73, 0x74, 0x5f, 0x74, 0x78, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x66, 0x69, 0x72, 0x73, 0x74, 0x54, 0x78, 0x48, 0x61, 0x73,
	0x68, 0x12, 0x34, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x40, 0x0a, 0x0d, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x5f, 0x74, 0x78, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x01, 0x52, 0x0b, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x54, 0x78, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3e, 0x0a, 0x0c, 0x6c, 0x61, 0x73,
	0x74, 0x5f, 0x74, 0x78, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x02, 0x52, 0x0a, 0x6c,
	0x61, 0x73, 0x74, 0x54, 0x78, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x5f, 0x74, 0x78, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x04, 0x48, 0x03, 0x52, 0x0d, 0x66, 0x69, 0x72, 0x73, 0x74, 0x54, 0x78, 0x48, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x74, 0x78, 0x5f, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x48, 0x04, 0x52, 0x0c, 0x6c,
	0x61, 0x73, 0x74, 0x54, 0x78, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x42, 0x13, 0x0a, 0x11, 0x6f,
	0x70, 0x74, 0x5f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x74, 0x78, 0x5f, 0x68, 0x61, 0x73, 0x68,
	0x42, 0x13, 0x0a, 0x11, 0x6f, 0x70, 0x74, 0x5f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x74, 0x78,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x12, 0x0a, 0x10, 0x6f, 0x70, 0x74, 0x5f, 0x6c, 0x61, 0x73,
	0x74, 0x5f, 0x74, 0x78, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x15, 0x0a, 0x13, 0x6f, 0x70, 0x74,
	0x5f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x74, 0x78, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x42, 0x14, 0x0a, 0x12, 0x6f, 0x70, 0x74, 0x5f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x74, 0x78, 0x5f,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x70, 0x0a, 0x13, 0x41, 0x73, 0x73, 0x65, 0x74, 0x50,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x1b, 0x0a,
	0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x5f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x0c, 0x66, 0x69, 0x72, 0x73, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x49, 0x64, 0x42, 0x14, 0x0a, 0x12, 0x6f, 0x70, 0x74, 0x5f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x22, 0x2b, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x22, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x2f, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x82, 0x01, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x49, 0x0a, 0x0f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x54,
	0x78, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x0e, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x22,
	0xa2, 0x01, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x49, 0x0a, 0x0f, 0x70, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x54, 0x78, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4d, 0x65, 0x74, 0x61, 0x52, 0x0e, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4d, 0x65, 0x74, 0x61, 0x22, 0x2e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x78, 0x5f, 0x68, 0x61,
	0x73, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x74, 0x78, 0x48, 0x61,
	0x73, 0x68, 0x65, 0x73, 0x22, 0x7f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x4c, 0x0a, 0x0f, 0x70, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x0e, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4d, 0x65, 0x74, 0x61, 0x22, 0x89, 0x01, 0x0a, 0x1b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x12, 0x4d, 0x0a, 0x0f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x69, 0x72,
	0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x49, 0x64, 0x52, 0x0d, 0x66, 0x69, 0x72, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49,
	0x64, 0x22, 0xe2, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1f, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x06, 0x77,
	0x72, 0x69, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x06, 0x77,
	0x72, 0x69, 0x74, 0x65, 0x72, 0x12, 0x54, 0x0a, 0x0f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b,
	0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x50, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x0e, 0x70, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x42, 0x10, 0x0a, 0x0e, 0x6f,
	0x70, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x42, 0x09, 0x0a,
	0x07, 0x6f, 0x70, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x42, 0x0c, 0x0a, 0x0a, 0x6f, 0x70, 0x74, 0x5f,
	0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x22, 0x29, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x73, 0x73, 0x65, 0x74, 0x49,
	0x64, 0x22, 0x0a, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x2d, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x63, 0x0a, 0x16,
	0x47, 0x65, 0x74, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x49, 0x0a, 0x0f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x54, 0x78, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74,
	0x61, 0x52, 0x0e, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74,
	0x61, 0x22, 0x0a, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x50, 0x65, 0x65, 0x72, 0x73, 0x22, 0x88, 0x01,
	0x0a, 0x10, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65,
	0x74, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72,
	0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x22, 0x2c, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x45,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x12, 0x17, 0x0a,
	0x07, 0x74, 0x78, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x22, 0x9a, 0x0a, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x37, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x37, 0x0a, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69,
	0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x1a, 0x9e, 0x09, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x34,
	0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x69,
	0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04,
	0x6d, 0x65, 0x74, 0x61, 0x12, 0x3d, 0x0a, 0x0b, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x69, 0x72, 0x6f, 0x68,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x67, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x49, 0x0a, 0x0f, 0x67, 0x65, 0x74, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x69,
	0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0e,
	0x67, 0x65, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x62,
	0x0a, 0x18, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x26, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x48, 0x00, 0x52, 0x16, 0x67, 0x65, 0x74, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x72, 0x0a, 0x1e, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x69, 0x72, 0x6f,
	0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x48, 0x00, 0x52, 0x1b, 0x67, 0x65, 0x74, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x4c, 0x0a, 0x10, 0x67, 0x65, 0x74, 0x5f, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x48, 0x00, 0x52, 0x0f, 0x67, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x50, 0x0a, 0x12, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x73, 0x48, 0x00, 0x52, 0x10, 0x67, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x12, 0x50, 0x0a, 0x12, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x48, 0x00, 0x52, 0x10, 0x67, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x37, 0x0a, 0x09, 0x67, 0x65, 0x74, 0x5f,
	0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x72,
	0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x6f, 0x6c, 0x65, 0x73, 0x48, 0x00, 0x52, 0x08, 0x67, 0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65,
	0x73, 0x12, 0x56, 0x0a, 0x14, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x70, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x48, 0x00, 0x52, 0x12, 0x67, 0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x44, 0x0a, 0x0e, 0x67, 0x65, 0x74,
	0x5f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x48,
	0x00, 0x52, 0x0c, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x62, 0x0a, 0x18, 0x67, 0x65, 0x74, 0x5f, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x48, 0x00, 0x52, 0x16, 0x67, 0x65, 0x74,
	0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x37, 0x0a, 0x09, 0x67, 0x65, 0x74, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x48, 0x00, 0x52, 0x08, 0x67, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x37, 0x0a, 0x09,
	0x67, 0x65, 0x74, 0x5f, 0x70, 0x65, 0x65, 0x72, 0x73, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x65, 0x72, 0x73, 0x48, 0x00, 0x52, 0x08, 0x67, 0x65, 0x74,
	0x50, 0x65, 0x65, 0x72, 0x73, 0x12, 0x53, 0x0a, 0x13, 0x67, 0x65, 0x74, 0x5f, 0x65, 0x6e, 0x67,
	0x69, 0x6e, 0x65, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x18, 0x10, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x70, 0x74, 0x73, 0x48, 0x00, 0x52, 0x11, 0x67, 0x65, 0x74, 0x45, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x73, 0x42, 0x07, 0x0a, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x22, 0x7c, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x12, 0x34, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65,
	0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x37, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69, 0x72,
	0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x2a, 0x28, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x10, 0x0a, 0x0c, 0x6b, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09,
	0x6b, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x01, 0x2a, 0x2c, 0x0a, 0x09, 0x44,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x0a, 0x6b, 0x41, 0x73, 0x63,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x6b, 0x44, 0x65, 0x73,
	0x63, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x42, 0x1a, 0x5a, 0x18, 0x69, 0x72, 0x6f,
	0x68, 0x61, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_queries_proto_rawDescOnce sync.Once
	file_queries_proto_rawDescData = file_queries_proto_rawDesc
)

func file_queries_proto_rawDescGZIP() []byte {
	file_queries_proto_rawDescOnce.Do(func() {
		file_queries_proto_rawDescData = protoimpl.X.CompressGZIP(file_queries_proto_rawDescData)
	})
	return file_queries_proto_rawDescData
}

var file_queries_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_queries_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_queries_proto_goTypes = []interface{}{
	(Field)(0),                          // 0: iroha.protocol.Field
	(Direction)(0),                      // 1: iroha.protocol.Direction
	(*Ordering)(nil),                    // 2: iroha.protocol.Ordering
	(*TxPaginationMeta)(nil),            // 3: iroha.protocol.TxPaginationMeta
	(*AssetPaginationMeta)(nil),         // 4: iroha.protocol.AssetPaginationMeta
	(*GetAccount)(nil),                  // 5: iroha.protocol.GetAccount
	(*GetBlock)(nil),                    // 6: iroha.protocol.GetBlock
	(*GetSignatories)(nil),              // 7: iroha.protocol.GetSignatories
	(*GetAccountTransactions)(nil),      // 8: iroha.protocol.GetAccountTransactions
	(*GetAccountAssetTransactions)(nil), // 9: iroha.protocol.GetAccountAssetTransactions
	(*GetTransactions)(nil),             // 10: iroha.protocol.GetTransactions
	(*GetAccountAssets)(nil),            // 11: iroha.protocol.GetAccountAssets
	(*AccountDetailPaginationMeta)(nil), // 12: iroha.protocol.AccountDetailPaginationMeta
	(*GetAccountDetail)(nil),            // 13: iroha.protocol.GetAccountDetail
	(*GetAssetInfo)(nil),                // 14: iroha.protocol.GetAssetInfo
	(*GetRoles)(nil),                    // 15: iroha.protocol.GetRoles
	(*GetRolePermissions)(nil),          // 16: iroha.protocol.GetRolePermissions
	(*GetPendingTransactions)(nil),      // 17: iroha.protocol.GetPendingTransactions
	(*GetPeers)(nil),                    // 18: iroha.protocol.GetPeers
	(*QueryPayloadMeta)(nil),            // 19: iroha.protocol.QueryPayloadMeta
	(*GetEngineReceipts)(nil),           // 20: iroha.protocol.GetEngineReceipts
	(*Query)(nil),                       // 21: iroha.protocol.Query
	(*BlocksQuery)(nil),                 // 22: iroha.protocol.BlocksQuery
	(*Ordering_FieldOrdering)(nil),      // 23: iroha.protocol.Ordering.FieldOrdering
	(*Query_Payload)(nil),               // 24: iroha.protocol.Query.Payload
	(*timestamp.Timestamp)(nil),         // 25: google.protobuf.Timestamp
	(*AccountDetailRecordId)(nil),       // 26: iroha.protocol.AccountDetailRecordId
	(*Signature)(nil),                   // 27: iroha.protocol.Signature
}
var file_queries_proto_depIdxs = []int32{
	23, // 0: iroha.protocol.Ordering.sequence:type_name -> iroha.protocol.Ordering.FieldOrdering
	2,  // 1: iroha.protocol.TxPaginationMeta.ordering:type_name -> iroha.protocol.Ordering
	25, // 2: iroha.protocol.TxPaginationMeta.first_tx_time:type_name -> google.protobuf.Timestamp
	25, // 3: iroha.protocol.TxPaginationMeta.last_tx_time:type_name -> google.protobuf.Timestamp
	3,  // 4: iroha.protocol.GetAccountTransactions.pagination_meta:type_name -> iroha.protocol.TxPaginationMeta
	3,  // 5: iroha.protocol.GetAccountAssetTransactions.pagination_meta:type_name -> iroha.protocol.TxPaginationMeta
	4,  // 6: iroha.protocol.GetAccountAssets.pagination_meta:type_name -> iroha.protocol.AssetPaginationMeta
	26, // 7: iroha.protocol.AccountDetailPaginationMeta.first_record_id:type_name -> iroha.protocol.AccountDetailRecordId
	12, // 8: iroha.protocol.GetAccountDetail.pagination_meta:type_name -> iroha.protocol.AccountDetailPaginationMeta
	3,  // 9: iroha.protocol.GetPendingTransactions.pagination_meta:type_name -> iroha.protocol.TxPaginationMeta
	24, // 10: iroha.protocol.Query.payload:type_name -> iroha.protocol.Query.Payload
	27, // 11: iroha.protocol.Query.signature:type_name -> iroha.protocol.Signature
	19, // 12: iroha.protocol.BlocksQuery.meta:type_name -> iroha.protocol.QueryPayloadMeta
	27, // 13: iroha.protocol.BlocksQuery.signature:type_name -> iroha.protocol.Signature
	0,  // 14: iroha.protocol.Ordering.FieldOrdering.field:type_name -> iroha.protocol.Field
	1,  // 15: iroha.protocol.Ordering.FieldOrdering.direction:type_name -> iroha.protocol.Direction
	19, // 16: iroha.protocol.Query.Payload.meta:type_name -> iroha.protocol.QueryPayloadMeta
	5,  // 17: iroha.protocol.Query.Payload.get_account:type_name -> iroha.protocol.GetAccount
	7,  // 18: iroha.protocol.Query.Payload.get_signatories:type_name -> iroha.protocol.GetSignatories
	8,  // 19: iroha.protocol.Query.Payload.get_account_transactions:type_name -> iroha.protocol.GetAccountTransactions
	9,  // 20: iroha.protocol.Query.Payload.get_account_asset_transactions:type_name -> iroha.protocol.GetAccountAssetTransactions
	10, // 21: iroha.protocol.Query.Payload.get_transactions:type_name -> iroha.protocol.GetTransactions
	11, // 22: iroha.protocol.Query.Payload.get_account_assets:type_name -> iroha.protocol.GetAccountAssets
	13, // 23: iroha.protocol.Query.Payload.get_account_detail:type_name -> iroha.protocol.GetAccountDetail
	15, // 24: iroha.protocol.Query.Payload.get_roles:type_name -> iroha.protocol.GetRoles
	16, // 25: iroha.protocol.Query.Payload.get_role_permissions:type_name -> iroha.protocol.GetRolePermissions
	14, // 26: iroha.protocol.Query.Payload.get_asset_info:type_name -> iroha.protocol.GetAssetInfo
	17, // 27: iroha.protocol.Query.Payload.get_pending_transactions:type_name -> iroha.protocol.GetPendingTransactions
	6,  // 28: iroha.protocol.Query.Payload.get_block:type_name -> iroha.protocol.GetBlock
	18, // 29: iroha.protocol.Query.Payload.get_peers:type_name -> iroha.protocol.GetPeers
	20, // 30: iroha.protocol.Query.Payload.get_engine_receipts:type_name -> iroha.protocol.GetEngineReceipts
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_queries_proto_init() }
func file_queries_proto_init() {
	if File_queries_proto != nil {
		return
	}
	file_primitive_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_queries_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ordering); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxPaginationMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssetPaginationMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSignatories); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountTransactions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountAssetTransactions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTransactions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountAssets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountDetailPaginationMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAssetInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRolePermissions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPendingTransactions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPeers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryPayloadMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEngineReceipts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlocksQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ordering_FieldOrdering); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_queries_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_queries_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*TxPaginationMeta_FirstTxHash)(nil),
		(*TxPaginationMeta_FirstTxTime)(nil),
		(*TxPaginationMeta_LastTxTime)(nil),
		(*TxPaginationMeta_FirstTxHeight)(nil),
		(*TxPaginationMeta_LastTxHeight)(nil),
	}
	file_queries_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*AssetPaginationMeta_FirstAssetId)(nil),
	}
	file_queries_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*GetAccountDetail_AccountId)(nil),
		(*GetAccountDetail_Key)(nil),
		(*GetAccountDetail_Writer)(nil),
	}
	file_queries_proto_msgTypes[22].OneofWrappers = []interface{}{
		(*Query_Payload_GetAccount)(nil),
		(*Query_Payload_GetSignatories)(nil),
		(*Query_Payload_GetAccountTransactions)(nil),
		(*Query_Payload_GetAccountAssetTransactions)(nil),
		(*Query_Payload_GetTransactions)(nil),
		(*Query_Payload_GetAccountAssets)(nil),
		(*Query_Payload_GetAccountDetail)(nil),
		(*Query_Payload_GetRoles)(nil),
		(*Query_Payload_GetRolePermissions)(nil),
		(*Query_Payload_GetAssetInfo)(nil),
		(*Query_Payload_GetPendingTransactions)(nil),
		(*Query_Payload_GetBlock)(nil),
		(*Query_Payload_GetPeers)(nil),
		(*Query_Payload_GetEngineReceipts)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_queries_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_queries_proto_goTypes,
		DependencyIndexes: file_queries_proto_depIdxs,
		EnumInfos:         file_queries_proto_enumTypes,
		MessageInfos:      file_queries_proto_msgTypes,
	}.Build()
	File_queries_proto = out.File
	file_queries_proto_rawDesc = nil
	file_queries_proto_goTypes = nil
	file_queries_proto_depIdxs = nil
}
