//*
// Copyright Soramitsu Co., Ltd. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.11.2
// source: transaction.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction_Payload_BatchMeta_BatchType int32

const (
	Transaction_Payload_BatchMeta_ATOMIC  Transaction_Payload_BatchMeta_BatchType = 0
	Transaction_Payload_BatchMeta_ORDERED Transaction_Payload_BatchMeta_BatchType = 1
)

// Enum value maps for Transaction_Payload_BatchMeta_BatchType.
var (
	Transaction_Payload_BatchMeta_BatchType_name = map[int32]string{
		0: "ATOMIC",
		1: "ORDERED",
	}
	Transaction_Payload_BatchMeta_BatchType_value = map[string]int32{
		"ATOMIC":  0,
		"ORDERED": 1,
	}
)

func (x Transaction_Payload_BatchMeta_BatchType) Enum() *Transaction_Payload_BatchMeta_BatchType {
	p := new(Transaction_Payload_BatchMeta_BatchType)
	*p = x
	return p
}

func (x Transaction_Payload_BatchMeta_BatchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transaction_Payload_BatchMeta_BatchType) Descriptor() protoreflect.EnumDescriptor {
	return file_transaction_proto_enumTypes[0].Descriptor()
}

func (Transaction_Payload_BatchMeta_BatchType) Type() protoreflect.EnumType {
	return &file_transaction_proto_enumTypes[0]
}

func (x Transaction_Payload_BatchMeta_BatchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transaction_Payload_BatchMeta_BatchType.Descriptor instead.
func (Transaction_Payload_BatchMeta_BatchType) EnumDescriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

type Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload    *Transaction_Payload `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signatures []*Signature         `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty"`
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetPayload() *Transaction_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Transaction) GetSignatures() []*Signature {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type Transaction_Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// transaction fields
	ReducedPayload *Transaction_Payload_ReducedPayload `protobuf:"bytes,1,opt,name=reduced_payload,json=reducedPayload,proto3" json:"reduced_payload,omitempty"`
	// batch meta fields if tx belong to any batch
	//
	// Types that are assignable to OptionalBatchMeta:
	//	*Transaction_Payload_Batch
	OptionalBatchMeta isTransaction_Payload_OptionalBatchMeta `protobuf_oneof:"optional_batch_meta"`
}

func (x *Transaction_Payload) Reset() {
	*x = Transaction_Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transaction_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Payload) ProtoMessage() {}

func (x *Transaction_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Payload.ProtoReflect.Descriptor instead.
func (*Transaction_Payload) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Transaction_Payload) GetReducedPayload() *Transaction_Payload_ReducedPayload {
	if x != nil {
		return x.ReducedPayload
	}
	return nil
}

func (m *Transaction_Payload) GetOptionalBatchMeta() isTransaction_Payload_OptionalBatchMeta {
	if m != nil {
		return m.OptionalBatchMeta
	}
	return nil
}

func (x *Transaction_Payload) GetBatch() *Transaction_Payload_BatchMeta {
	if x, ok := x.GetOptionalBatchMeta().(*Transaction_Payload_Batch); ok {
		return x.Batch
	}
	return nil
}

type isTransaction_Payload_OptionalBatchMeta interface {
	isTransaction_Payload_OptionalBatchMeta()
}

type Transaction_Payload_Batch struct {
	Batch *Transaction_Payload_BatchMeta `protobuf:"bytes,5,opt,name=batch,proto3,oneof"`
}

func (*Transaction_Payload_Batch) isTransaction_Payload_OptionalBatchMeta() {}

type Transaction_Payload_BatchMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type Transaction_Payload_BatchMeta_BatchType `protobuf:"varint,1,opt,name=type,proto3,enum=iroha.protocol.Transaction_Payload_BatchMeta_BatchType" json:"type,omitempty"`
	// array of reduced hashes of all txs from the batch
	ReducedHashes []string `protobuf:"bytes,2,rep,name=reduced_hashes,json=reducedHashes,proto3" json:"reduced_hashes,omitempty"`
}

func (x *Transaction_Payload_BatchMeta) Reset() {
	*x = Transaction_Payload_BatchMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transaction_Payload_BatchMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Payload_BatchMeta) ProtoMessage() {}

func (x *Transaction_Payload_BatchMeta) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Payload_BatchMeta.ProtoReflect.Descriptor instead.
func (*Transaction_Payload_BatchMeta) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Transaction_Payload_BatchMeta) GetType() Transaction_Payload_BatchMeta_BatchType {
	if x != nil {
		return x.Type
	}
	return Transaction_Payload_BatchMeta_ATOMIC
}

func (x *Transaction_Payload_BatchMeta) GetReducedHashes() []string {
	if x != nil {
		return x.ReducedHashes
	}
	return nil
}

type Transaction_Payload_ReducedPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commands         []*Command `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	CreatorAccountId string     `protobuf:"bytes,2,opt,name=creator_account_id,json=creatorAccountId,proto3" json:"creator_account_id,omitempty"`
	CreatedTime      uint64     `protobuf:"varint,3,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	Quorum           uint32     `protobuf:"varint,4,opt,name=quorum,proto3" json:"quorum,omitempty"`
}

func (x *Transaction_Payload_ReducedPayload) Reset() {
	*x = Transaction_Payload_ReducedPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transaction_Payload_ReducedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Payload_ReducedPayload) ProtoMessage() {}

func (x *Transaction_Payload_ReducedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Payload_ReducedPayload.ProtoReflect.Descriptor instead.
func (*Transaction_Payload_ReducedPayload) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *Transaction_Payload_ReducedPayload) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *Transaction_Payload_ReducedPayload) GetCreatorAccountId() string {
	if x != nil {
		return x.CreatorAccountId
	}
	return ""
}

func (x *Transaction_Payload_ReducedPayload) GetCreatedTime() uint64 {
	if x != nil {
		return x.CreatedTime
	}
	return 0
}

func (x *Transaction_Payload_ReducedPayload) GetQuorum() uint32 {
	if x != nil {
		return x.Quorum
	}
	return 0
}

var File_transaction_proto protoreflect.FileDescriptor

var file_transaction_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x1a, 0x0e, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x70, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa7, 0x05, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3d, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x52, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x1a, 0x9d,
	0x04, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x5b, 0x0a, 0x0f, 0x72, 0x65,
	0x64, 0x75, 0x63, 0x65, 0x64, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x64,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x0e, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x64,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x45, 0x0a, 0x05, 0x62, 0x61, 0x74, 0x63, 0x68,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x4d, 0x65, 0x74, 0x61, 0x48, 0x00, 0x52, 0x05, 0x62, 0x61, 0x74, 0x63, 0x68, 0x1a, 0xa5,
	0x01, 0x0a, 0x09, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x4b, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x37, 0x2e, 0x69, 0x72, 0x6f,
	0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x4d, 0x65, 0x74, 0x61, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x64,
	0x75, 0x63, 0x65, 0x64, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0d, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x64, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73,
	0x22, 0x24, 0x0a, 0x09, 0x42, 0x61, 0x74, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a,
	0x06, 0x41, 0x54, 0x4f, 0x4d, 0x49, 0x43, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x52, 0x44,
	0x45, 0x52, 0x45, 0x44, 0x10, 0x01, 0x1a, 0xae, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x64, 0x75, 0x63,
	0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x33, 0x0a, 0x08, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x69, 0x72,
	0x6f, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x12, 0x2c,
	0x0a, 0x12, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x6f, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x42, 0x15, 0x0a, 0x13, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x5f, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x42, 0x1a,
	0x5a, 0x18, 0x69, 0x72, 0x6f, 0x68, 0x61, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_transaction_proto_rawDescOnce sync.Once
	file_transaction_proto_rawDescData = file_transaction_proto_rawDesc
)

func file_transaction_proto_rawDescGZIP() []byte {
	file_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(file_transaction_proto_rawDescData)
	})
	return file_transaction_proto_rawDescData
}

var file_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_transaction_proto_goTypes = []interface{}{
	(Transaction_Payload_BatchMeta_BatchType)(0), // 0: iroha.protocol.Transaction.Payload.BatchMeta.BatchType
	(*Transaction)(nil),                          // 1: iroha.protocol.Transaction
	(*Transaction_Payload)(nil),                  // 2: iroha.protocol.Transaction.Payload
	(*Transaction_Payload_BatchMeta)(nil),        // 3: iroha.protocol.Transaction.Payload.BatchMeta
	(*Transaction_Payload_ReducedPayload)(nil),   // 4: iroha.protocol.Transaction.Payload.ReducedPayload
	(*Signature)(nil),                            // 5: iroha.protocol.Signature
	(*Command)(nil),                              // 6: iroha.protocol.Command
}
var file_transaction_proto_depIdxs = []int32{
	2, // 0: iroha.protocol.Transaction.payload:type_name -> iroha.protocol.Transaction.Payload
	5, // 1: iroha.protocol.Transaction.signatures:type_name -> iroha.protocol.Signature
	4, // 2: iroha.protocol.Transaction.Payload.reduced_payload:type_name -> iroha.protocol.Transaction.Payload.ReducedPayload
	3, // 3: iroha.protocol.Transaction.Payload.batch:type_name -> iroha.protocol.Transaction.Payload.BatchMeta
	0, // 4: iroha.protocol.Transaction.Payload.BatchMeta.type:type_name -> iroha.protocol.Transaction.Payload.BatchMeta.BatchType
	6, // 5: iroha.protocol.Transaction.Payload.ReducedPayload.commands:type_name -> iroha.protocol.Command
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_transaction_proto_init() }
func file_transaction_proto_init() {
	if File_transaction_proto != nil {
		return
	}
	file_commands_proto_init()
	file_primitive_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_transaction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transaction_Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transaction_Payload_BatchMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transaction_Payload_ReducedPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_transaction_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Transaction_Payload_Batch)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transaction_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_proto_depIdxs,
		EnumInfos:         file_transaction_proto_enumTypes,
		MessageInfos:      file_transaction_proto_msgTypes,
	}.Build()
	File_transaction_proto = out.File
	file_transaction_proto_rawDesc = nil
	file_transaction_proto_goTypes = nil
	file_transaction_proto_depIdxs = nil
}
