iroha:
  api:
    host: localhost
    port: 50051
  postgres:
    host: localhost
    port: 5432
    user: iroha
    password: mysecretpassword
    database: iroha-data
gateway:
  rpc:
    host: localhost
    port: 8545
  accounts:
    - id: admin@test
      privateKey: f101537e319568c765b2cc89698325604991dca57b9716b58016b253506cab70
