FROM ghcr.io/hyperledger/iroha-builder:1.3.0

USER root

WORKDIR /opt/iroha
RUN git clone --branch 1.3.0 --depth 1 https://github.com/hyperledger/iroha.git

WORKDIR /opt/iroha/iroha
RUN ./vcpkg/build_iroha_deps.sh $PWD/vcpkg-build
