name: e2e-test
on:
  pull_request:

jobs:
  test-e2e:
    name: test-e2e
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/checkout@v2
      - name: Cache go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-e2e-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-e2e-
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ${{ github.workspace }}/onchain-module/node_modules
          key: ${{ runner.os }}-e2e-${{ hashFiles('onchain-module/tests/e2e/contracts/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-e2e-
      - name: Build relayer
        working-directory: relayer
        run: make build
      - name: Run docker-compose
        run: make network
      - name: Download NPM dependency
        working-directory: onchain-module
        run: |
          npm install
      - name: Migrate Contracts
        working-directory: onchain-module
        run: |
          make migrate-e2e
      - name: Run E2E Test
        run: |
          make e2e-test
