name: iroha-go
on:
  pull_request:
    paths:
      - "docker/**"
      - "iroha-go/**"
      - ".github/workflows/test-iroha-go.yml"

jobs:
  test-e2e:
    name: test-e2e
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
      - name: Cache go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-iroha-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-iroha-go-
      - name: Run docker-compose
        run: docker compose up -d iroha-node0 iroha-node0-postgres
      - name: Run Unit Test for iroha-go
        working-directory: iroha-go
        run: |
          make test-all
